#!/bin/bash
#
# generate-compose.sh — Generate a docker-compose.yml for N validators.
#
# Usage:
#   bash docker/generate-compose.sh [NUM_VALIDATORS]
#
# Default: 30 validators. Output: docker/docker-compose.yml
set -e

NUM="${1:-30}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$SCRIPT_DIR/docker-compose.yml"

cat > "$OUT" <<'HEADER'
# Auto-generated by generate-compose.sh — do not edit manually.
services:
HEADER

for i in $(seq 1 "$NUM"); do
    NAME="val${i}"
    cat >> "$OUT" <<EOF
  ${NAME}:
    image: svoted-testnet
    container_name: ${NAME}
    hostname: ${NAME}
    environment:
      - VALIDATOR_INDEX=${i}
      - NUM_VALIDATORS=${NUM}
      - CHAIN_ID=svote-1
    volumes:
      - shared:/shared
    networks:
      - testnet
EOF

    # Only val1 exposes ports to the host.
    if [ "$i" -eq 1 ]; then
        cat >> "$OUT" <<'EOF'
    ports:
      - "26157:26657"
      - "1317:1317"
EOF
    fi

    echo "" >> "$OUT"
done

# Block explorer: archive node (historical queries) + ping-pub frontend.
cat >> "$OUT" <<EOF
  archive:
    image: svoted-testnet
    container_name: archive
    hostname: archive
    environment:
      - ROLE=archive
      - NUM_VALIDATORS=${NUM}
      - CHAIN_ID=svote-1
    volumes:
      - shared:/shared
    networks:
      - testnet
    ports:
      - "1917:1317"
      - "27657:26657"
    depends_on:
      - val1

  explorer:
    build: ./ping-pub
    container_name: explorer
    hostname: explorer
    ports:
      - "8080:80"
    networks:
      - testnet
    depends_on:
      - archive

EOF

cat >> "$OUT" <<'FOOTER'
volumes:
  shared:

networks:
  testnet:
    driver: bridge
FOOTER

echo "Generated $OUT with $NUM validators + archive + explorer."
