package keeper

import (
	"context"
	"encoding/hex"
	"fmt"

	"cosmossdk.io/core/store"
	"cosmossdk.io/log"
	sdk "github.com/cosmos/cosmos-sdk/types"
	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
	"google.golang.org/protobuf/proto"

	"github.com/valargroup/vote-sdk/ffi/votetree"
	"github.com/valargroup/vote-sdk/x/vote/types"
)

// StakingKeeper defines the staking module interface needed by the vote module.
type StakingKeeper interface {
	GetValidator(ctx context.Context, addr sdk.ValAddress) (stakingtypes.Validator, error)
	GetValidatorByConsAddr(ctx context.Context, consAddr sdk.ConsAddress) (stakingtypes.Validator, error)
	Jail(ctx context.Context, consAddr sdk.ConsAddress) error
	Unjail(ctx context.Context, consAddr sdk.ConsAddress) error
}

// BankKeeper defines the bank module interface needed by the vote module.
// Used by MsgSetVoteManager to transfer the treasury balance atomically
// when reassigning the vote manager role.
type BankKeeper interface {
	GetBalance(ctx context.Context, addr sdk.AccAddress, denom string) sdk.Coin
	SendCoins(ctx context.Context, fromAddr, toAddr sdk.AccAddress, amt sdk.Coins) error
}

// roundTree holds the in-memory ShardTree state for a single voting round.
// Each active round gets its own proxy (with a round-scoped Prefix) and a
// lazily-initialized tree handle.
type roundTree struct {
	handle *votetree.TreeHandle    // lazy-initialized; nil until first EndBlock for this round
	proxy  *votetree.KvStoreProxy // Prefix = RoundTreeKey(roundID)
}

// Keeper of the vote module store.
//
// KV Store Layout:
//
//	0x01 || type || round_id || nf  -> []byte{1}         (nullifier set, scoped by type+round)
//	0x14 || round_id || 0x02 || uint64 index -> commitment_bytes (per-round commitment tree)
//	0x14 || round_id || 0x03 || uint64 height -> root_bytes      (per-round tree roots)
//	0x04 || round_id                -> VoteRound protobuf (vote round data)
//	0x05 || round_id || proposal_id || decision -> []byte (64 bytes: ElGamal ciphertext)
//	0x14 || round_id || 0x06        -> CommitmentTreeState protobuf (per-round tree metadata)
//
// Uses google.golang.org/protobuf/proto for binary marshal (our types are
// generated by protoc-gen-go, not gogoproto).
type Keeper struct {
	storeService  store.KVStoreService
	authority     string
	logger        log.Logger
	stakingKeeper StakingKeeper
	bankKeeper    BankKeeper

	// roundTrees holds per-round in-memory ShardTree state, keyed by the
	// hex-encoded round ID. Each entry has its own KvStoreProxy (with a
	// round-scoped Prefix) and a lazily-initialized TreeHandle.
	//
	// Concurrency: only EndBlocker (via ComputeTreeRoot) mutates this map.
	roundTrees map[string]*roundTree
}

// NewKeeper creates a new vote module keeper.
func NewKeeper(
	storeService store.KVStoreService,
	authority string,
	logger log.Logger,
	stakingKeeper StakingKeeper,
	bankKeeper BankKeeper,
) *Keeper {
	return &Keeper{
		storeService:  storeService,
		authority:     authority,
		logger:        logger.With("module", "x/"+types.ModuleName),
		stakingKeeper: stakingKeeper,
		bankKeeper:    bankKeeper,
		roundTrees:    make(map[string]*roundTree),
	}
}

// getOrCreateRoundTree returns the per-round tree state, creating it lazily
// if this is the first access for the given round.
func (k *Keeper) getOrCreateRoundTree(roundID []byte) *roundTree {
	key := hex.EncodeToString(roundID)
	rt, ok := k.roundTrees[key]
	if ok {
		return rt
	}
	rt = &roundTree{
		proxy: &votetree.KvStoreProxy{
			Prefix: types.RoundTreeKey(roundID),
		},
	}
	k.roundTrees[key] = rt
	return rt
}

// ensureRoundTreeLoaded brings the per-round treeHandle up to date with
// nextIndex leaves from KV.
//
// Cases:
//   - handle == nil, Height > 0 (restart): shard/cap/checkpoint blobs
//     exist in KV from the previous process. Create handle at nextIndex;
//     ShardTree restores lazily from KV — O(1) cold start.
//   - handle == nil, Height == 0 (first boot): no shard data in KV yet.
//     Create handle at position 0 and fall through to the delta-append path
//     so all leaves [0, nextIndex) are replayed via AppendFromKV. O(N) but
//     unavoidable since the ShardTree has never been populated.
//   - Size() == nextIndex: already up to date, no-op.
//   - Size() < nextIndex (delta): append leaves [Size(), nextIndex) from KV.
//   - Size() > nextIndex: invariant violation — returns an error.
//
// Returns (needsCheckpoint, error). Caller should call Checkpoint(blockHeight)
// when needsCheckpoint is true.
//
// Not safe for concurrent use. Must only be called from the single-threaded
// EndBlocker path (via ComputeTreeRoot).
func (k *Keeper) ensureRoundTreeLoaded(kvStore store.KVStore, roundID []byte, nextIndex uint64) (needsCheckpoint bool, err error) {
	rt := k.getOrCreateRoundTree(roundID)
	rt.proxy.SetStore(kvStore)

	if rt.handle == nil {
		state, err := k.GetCommitmentTreeState(kvStore, roundID)
		if err != nil {
			return false, fmt.Errorf("ensureRoundTreeLoaded: read tree state: %w", err)
		}

		if state.Height > 0 {
			h, err := votetree.NewTreeHandleWithKV(rt.proxy, nextIndex)
			if err != nil {
				return false, fmt.Errorf("ensureRoundTreeLoaded: restart: %w", err)
			}
			rt.handle = h
			return false, nil
		}

		h, err := votetree.NewTreeHandleWithKV(rt.proxy, 0)
		if err != nil {
			return false, fmt.Errorf("ensureRoundTreeLoaded: first boot: %w", err)
		}
		rt.handle = h
	}

	size := rt.handle.Size()

	if size > nextIndex {
		return false, fmt.Errorf("ensureRoundTreeLoaded: tree size %d > nextIndex %d: invariant violated", size, nextIndex)
	}

	if size == nextIndex {
		return false, nil
	}

	if err := rt.handle.AppendFromKV(size, nextIndex-size); err != nil {
		return false, err
	}
	return true, nil
}

// OpenKVStore opens the module's KV store from a context.
func (k *Keeper) OpenKVStore(ctx context.Context) store.KVStore {
	return k.storeService.OpenKVStore(ctx)
}

// marshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func marshal(m proto.Message) ([]byte, error) {
	return proto.Marshal(m)
}

// unmarshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func unmarshal(bz []byte, m proto.Message) error {
	return proto.Unmarshal(bz, m)
}

// GetAuthority returns the module's authority address.
func (k *Keeper) GetAuthority() string {
	return k.authority
}

// Logger returns a module-specific logger.
func (k *Keeper) Logger() log.Logger {
	return k.logger
}

// ---------------------------------------------------------------------------
// VoteRound CRUD
// ---------------------------------------------------------------------------

// GetVoteRound retrieves a vote round by its ID.
func (k *Keeper) GetVoteRound(kvStore store.KVStore, roundID []byte) (*types.VoteRound, error) {
	key, err := types.VoteRoundKey(roundID)
	if err != nil {
		return nil, err
	}
	bz, err := kvStore.Get(key)
	if err != nil {
		return nil, err
	}
	if bz == nil {
		return nil, types.ErrRoundNotFound
	}

	var round types.VoteRound
	if err := unmarshal(bz, &round); err != nil {
		return nil, err
	}
	return &round, nil
}

// SetVoteRound stores a vote round.
func (k *Keeper) SetVoteRound(kvStore store.KVStore, round *types.VoteRound) error {
	bz, err := marshal(round)
	if err != nil {
		return err
	}
	key, err := types.VoteRoundKey(round.VoteRoundId)
	if err != nil {
		return err
	}
	return kvStore.Set(key, bz)
}

// ---------------------------------------------------------------------------
// Round status management
// ---------------------------------------------------------------------------

// UpdateVoteRoundStatus reads a vote round, sets its status, and writes it back.
func (k *Keeper) UpdateVoteRoundStatus(kvStore store.KVStore, roundID []byte, newStatus types.SessionStatus) error {
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err
	}
	round.Status = newStatus
	return k.SetVoteRound(kvStore, round)
}

// ---------------------------------------------------------------------------
// Round iterators
// ---------------------------------------------------------------------------

// IterateAllRounds iterates over all stored VoteRounds and calls the
// callback for each round. The callback receives a pointer to the round;
// returning true stops iteration.
//
// This performs a full prefix scan of VoteRoundPrefix. This is acceptable
// because the expected cardinality is low (a handful of rounds).
func (k *Keeper) IterateAllRounds(kvStore store.KVStore, cb func(round *types.VoteRound) bool) error {
	return k.iterateRounds(kvStore, nil, cb)
}

// IteratePendingRounds iterates over rounds with SESSION_STATUS_PENDING.
func (k *Keeper) IteratePendingRounds(kvStore store.KVStore, cb func(round *types.VoteRound) bool) error {
	return k.iterateRounds(kvStore, func(r *types.VoteRound) bool {
		return r.Status == types.SessionStatus_SESSION_STATUS_PENDING
	}, cb)
}

// IterateActiveRounds iterates over rounds with SESSION_STATUS_ACTIVE.
func (k *Keeper) IterateActiveRounds(kvStore store.KVStore, cb func(round *types.VoteRound) bool) error {
	return k.iterateRounds(kvStore, func(r *types.VoteRound) bool {
		return r.Status == types.SessionStatus_SESSION_STATUS_ACTIVE
	}, cb)
}

// IterateTallyingRounds iterates over rounds with SESSION_STATUS_TALLYING.
func (k *Keeper) IterateTallyingRounds(kvStore store.KVStore, cb func(round *types.VoteRound) bool) error {
	return k.iterateRounds(kvStore, func(r *types.VoteRound) bool {
		return r.Status == types.SessionStatus_SESSION_STATUS_TALLYING
	}, cb)
}

// HasPendingRound returns true if any stored VoteRound has status PENDING.
func (k *Keeper) HasPendingRound(kvStore store.KVStore) (bool, error) {
	found := false
	err := k.IteratePendingRounds(kvStore, func(_ *types.VoteRound) bool {
		found = true
		return true
	})
	return found, err
}

// FindFirstPendingRound returns the first VoteRound with status PENDING and
// the given CeremonyStatus, or nil if none found.
func (k *Keeper) FindFirstPendingRound(kvStore store.KVStore, ceremonyStatus types.CeremonyStatus) (*types.VoteRound, error) {
	var result *types.VoteRound
	err := k.IteratePendingRounds(kvStore, func(round *types.VoteRound) bool {
		if round.CeremonyStatus == ceremonyStatus {
			result = round
			return true
		}
		return false
	})
	return result, err
}

// iterateRounds is the core prefix-scan loop. If filter is non-nil, only
// rounds passing the filter are forwarded to cb. Returning true from cb
// stops iteration.
func (k *Keeper) iterateRounds(kvStore store.KVStore, filter func(*types.VoteRound) bool, cb func(*types.VoteRound) bool) error {
	prefix := types.VoteRoundPrefix
	end := types.PrefixEndBytes(prefix)

	iter, err := kvStore.Iterator(prefix, end)
	if err != nil {
		return err
	}
	defer iter.Close()

	for ; iter.Valid(); iter.Next() {
		var round types.VoteRound
		if err := unmarshal(iter.Value(), &round); err != nil {
			return err
		}
		if filter != nil && !filter(&round) {
			continue
		}
		if cb(&round) {
			break
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Byte helpers
// ---------------------------------------------------------------------------

// getUint32BE reads a uint32 from big-endian bytes.
func getUint32BE(b []byte) uint32 {
	return uint32(b[0])<<24 | uint32(b[1])<<16 | uint32(b[2])<<8 | uint32(b[3])
}

// putUint64BE writes a uint64 in big-endian byte order.
func putUint64BE(b []byte, v uint64) {
	b[0] = byte(v >> 56)
	b[1] = byte(v >> 48)
	b[2] = byte(v >> 40)
	b[3] = byte(v >> 32)
	b[4] = byte(v >> 24)
	b[5] = byte(v >> 16)
	b[6] = byte(v >> 8)
	b[7] = byte(v)
}

// getUint64BE reads a uint64 from big-endian bytes.
func getUint64BE(b []byte) uint64 {
	return uint64(b[0])<<56 | uint64(b[1])<<48 | uint64(b[2])<<40 | uint64(b[3])<<32 |
		uint64(b[4])<<24 | uint64(b[5])<<16 | uint64(b[6])<<8 | uint64(b[7])
}
