// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: svote/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryCommitmentTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	VoteRoundId   []byte                 `protobuf:"bytes,2,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCommitmentTreeRequest) Reset() {
	*x = QueryCommitmentTreeRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentTreeRequest) ProtoMessage() {}

func (x *QueryCommitmentTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentTreeRequest.ProtoReflect.Descriptor instead.
func (*QueryCommitmentTreeRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryCommitmentTreeRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *QueryCommitmentTreeRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryCommitmentTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *CommitmentTreeState   `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCommitmentTreeResponse) Reset() {
	*x = QueryCommitmentTreeResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentTreeResponse) ProtoMessage() {}

func (x *QueryCommitmentTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentTreeResponse.ProtoReflect.Descriptor instead.
func (*QueryCommitmentTreeResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryCommitmentTreeResponse) GetTree() *CommitmentTreeState {
	if x != nil {
		return x.Tree
	}
	return nil
}

type QueryLatestTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestTreeRequest) Reset() {
	*x = QueryLatestTreeRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestTreeRequest) ProtoMessage() {}

func (x *QueryLatestTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestTreeRequest.ProtoReflect.Descriptor instead.
func (*QueryLatestTreeRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryLatestTreeRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryLatestTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *CommitmentTreeState   `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestTreeResponse) Reset() {
	*x = QueryLatestTreeResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestTreeResponse) ProtoMessage() {}

func (x *QueryLatestTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestTreeResponse.ProtoReflect.Descriptor instead.
func (*QueryLatestTreeResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLatestTreeResponse) GetTree() *CommitmentTreeState {
	if x != nil {
		return x.Tree
	}
	return nil
}

type QueryVoteRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteRoundRequest) Reset() {
	*x = QueryVoteRoundRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteRoundRequest) ProtoMessage() {}

func (x *QueryVoteRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteRoundRequest.ProtoReflect.Descriptor instead.
func (*QueryVoteRoundRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryVoteRoundRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryVoteRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         *VoteRound             `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteRoundResponse) Reset() {
	*x = QueryVoteRoundResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteRoundResponse) ProtoMessage() {}

func (x *QueryVoteRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteRoundResponse.ProtoReflect.Descriptor instead.
func (*QueryVoteRoundResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVoteRoundResponse) GetRound() *VoteRound {
	if x != nil {
		return x.Round
	}
	return nil
}

type QueryProposalTallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalTallyRequest) Reset() {
	*x = QueryProposalTallyRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalTallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalTallyRequest) ProtoMessage() {}

func (x *QueryProposalTallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalTallyRequest.ProtoReflect.Descriptor instead.
func (*QueryProposalTallyRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryProposalTallyRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *QueryProposalTallyRequest) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type QueryProposalTallyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mapping from vote_decision to serialized ElGamal ciphertext (64 bytes each).
	Tally         map[uint32][]byte `protobuf:"bytes,1,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalTallyResponse) Reset() {
	*x = QueryProposalTallyResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalTallyResponse) ProtoMessage() {}

func (x *QueryProposalTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalTallyResponse.ProtoReflect.Descriptor instead.
func (*QueryProposalTallyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryProposalTallyResponse) GetTally() map[uint32][]byte {
	if x != nil {
		return x.Tally
	}
	return nil
}

type QueryTallyResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultsRequest) Reset() {
	*x = QueryTallyResultsRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultsRequest) ProtoMessage() {}

func (x *QueryTallyResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultsRequest.ProtoReflect.Descriptor instead.
func (*QueryTallyResultsRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTallyResultsRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryTallyResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TallyResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultsResponse) Reset() {
	*x = QueryTallyResultsResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultsResponse) ProtoMessage() {}

func (x *QueryTallyResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultsResponse.ProtoReflect.Descriptor instead.
func (*QueryTallyResultsResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryTallyResultsResponse) GetResults() []*TallyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type QueryPartialDecryptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPartialDecryptionsRequest) Reset() {
	*x = QueryPartialDecryptionsRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPartialDecryptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPartialDecryptionsRequest) ProtoMessage() {}

func (x *QueryPartialDecryptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPartialDecryptionsRequest.ProtoReflect.Descriptor instead.
func (*QueryPartialDecryptionsRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryPartialDecryptionsRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryPartialDecryptionsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entries       []*StoredPartialDecryption `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPartialDecryptionsResponse) Reset() {
	*x = QueryPartialDecryptionsResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPartialDecryptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPartialDecryptionsResponse) ProtoMessage() {}

func (x *QueryPartialDecryptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPartialDecryptionsResponse.ProtoReflect.Descriptor instead.
func (*QueryPartialDecryptionsResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryPartialDecryptionsResponse) GetEntries() []*StoredPartialDecryption {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StoredPartialDecryption struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorIndex uint32                 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	ProposalId     uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision   uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	PartialDecrypt []byte                 `protobuf:"bytes,4,opt,name=partial_decrypt,json=partialDecrypt,proto3" json:"partial_decrypt,omitempty"`
	DleqProof      []byte                 `protobuf:"bytes,5,opt,name=dleq_proof,json=dleqProof,proto3" json:"dleq_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoredPartialDecryption) Reset() {
	*x = StoredPartialDecryption{}
	mi := &file_svote_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredPartialDecryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredPartialDecryption) ProtoMessage() {}

func (x *StoredPartialDecryption) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredPartialDecryption.ProtoReflect.Descriptor instead.
func (*StoredPartialDecryption) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *StoredPartialDecryption) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *StoredPartialDecryption) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *StoredPartialDecryption) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *StoredPartialDecryption) GetPartialDecrypt() []byte {
	if x != nil {
		return x.PartialDecrypt
	}
	return nil
}

func (x *StoredPartialDecryption) GetDleqProof() []byte {
	if x != nil {
		return x.DleqProof
	}
	return nil
}

type QueryCommitmentLeavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHeight    uint64                 `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight      uint64                 `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	VoteRoundId   []byte                 `protobuf:"bytes,3,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCommitmentLeavesRequest) Reset() {
	*x = QueryCommitmentLeavesRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentLeavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentLeavesRequest) ProtoMessage() {}

func (x *QueryCommitmentLeavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentLeavesRequest.ProtoReflect.Descriptor instead.
func (*QueryCommitmentLeavesRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryCommitmentLeavesRequest) GetFromHeight() uint64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *QueryCommitmentLeavesRequest) GetToHeight() uint64 {
	if x != nil {
		return x.ToHeight
	}
	return 0
}

func (x *QueryCommitmentLeavesRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryCommitmentLeavesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Blocks         []*BlockCommitments    `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	NextFromHeight uint64                 `protobuf:"varint,2,opt,name=next_from_height,json=nextFromHeight,proto3" json:"next_from_height,omitempty"` // 0 when no more indexed leaf blocks remain in the requested range
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryCommitmentLeavesResponse) Reset() {
	*x = QueryCommitmentLeavesResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentLeavesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentLeavesResponse) ProtoMessage() {}

func (x *QueryCommitmentLeavesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentLeavesResponse.ProtoReflect.Descriptor instead.
func (*QueryCommitmentLeavesResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryCommitmentLeavesResponse) GetBlocks() []*BlockCommitments {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryCommitmentLeavesResponse) GetNextFromHeight() uint64 {
	if x != nil {
		return x.NextFromHeight
	}
	return 0
}

type QueryActiveRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActiveRoundRequest) Reset() {
	*x = QueryActiveRoundRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActiveRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveRoundRequest) ProtoMessage() {}

func (x *QueryActiveRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveRoundRequest.ProtoReflect.Descriptor instead.
func (*QueryActiveRoundRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{15}
}

type QueryActiveRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         *VoteRound             `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActiveRoundResponse) Reset() {
	*x = QueryActiveRoundResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActiveRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveRoundResponse) ProtoMessage() {}

func (x *QueryActiveRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveRoundResponse.ProtoReflect.Descriptor instead.
func (*QueryActiveRoundResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryActiveRoundResponse) GetRound() *VoteRound {
	if x != nil {
		return x.Round
	}
	return nil
}

type QueryCeremonyStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCeremonyStateRequest) Reset() {
	*x = QueryCeremonyStateRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCeremonyStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCeremonyStateRequest) ProtoMessage() {}

func (x *QueryCeremonyStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCeremonyStateRequest.ProtoReflect.Descriptor instead.
func (*QueryCeremonyStateRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{17}
}

type QueryCeremonyStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ceremony      *CeremonyState         `protobuf:"bytes,1,opt,name=ceremony,proto3" json:"ceremony,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCeremonyStateResponse) Reset() {
	*x = QueryCeremonyStateResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCeremonyStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCeremonyStateResponse) ProtoMessage() {}

func (x *QueryCeremonyStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCeremonyStateResponse.ProtoReflect.Descriptor instead.
func (*QueryCeremonyStateResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{18}
}

func (x *QueryCeremonyStateResponse) GetCeremony() *CeremonyState {
	if x != nil {
		return x.Ceremony
	}
	return nil
}

type QueryVoteManagersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteManagersRequest) Reset() {
	*x = QueryVoteManagersRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteManagersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteManagersRequest) ProtoMessage() {}

func (x *QueryVoteManagersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteManagersRequest.ProtoReflect.Descriptor instead.
func (*QueryVoteManagersRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{19}
}

type QueryVoteManagersResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VoteManagerAddresses  []string               `protobuf:"bytes,1,rep,name=vote_manager_addresses,json=voteManagerAddresses,proto3" json:"vote_manager_addresses,omitempty"`
	Threshold             uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	MinCeremonyValidators uint32                 `protobuf:"varint,3,opt,name=min_ceremony_validators,json=minCeremonyValidators,proto3" json:"min_ceremony_validators,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueryVoteManagersResponse) Reset() {
	*x = QueryVoteManagersResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteManagersResponse) ProtoMessage() {}

func (x *QueryVoteManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteManagersResponse.ProtoReflect.Descriptor instead.
func (*QueryVoteManagersResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{20}
}

func (x *QueryVoteManagersResponse) GetVoteManagerAddresses() []string {
	if x != nil {
		return x.VoteManagerAddresses
	}
	return nil
}

func (x *QueryVoteManagersResponse) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *QueryVoteManagersResponse) GetMinCeremonyValidators() uint32 {
	if x != nil {
		return x.MinCeremonyValidators
	}
	return 0
}

type QueryVoteSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteSummaryRequest) Reset() {
	*x = QueryVoteSummaryRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteSummaryRequest) ProtoMessage() {}

func (x *QueryVoteSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryVoteSummaryRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *QueryVoteSummaryRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryVoteSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=svote.v1.SessionStatus" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VoteEndTime   uint64                 `protobuf:"varint,4,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	Proposals     []*ProposalSummary     `protobuf:"bytes,5,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteSummaryResponse) Reset() {
	*x = QueryVoteSummaryResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteSummaryResponse) ProtoMessage() {}

func (x *QueryVoteSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryVoteSummaryResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{22}
}

func (x *QueryVoteSummaryResponse) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *QueryVoteSummaryResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *QueryVoteSummaryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QueryVoteSummaryResponse) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *QueryVoteSummaryResponse) GetProposals() []*ProposalSummary {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type QueryListRoundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListRoundsRequest) Reset() {
	*x = QueryListRoundsRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListRoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListRoundsRequest) ProtoMessage() {}

func (x *QueryListRoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListRoundsRequest.ProtoReflect.Descriptor instead.
func (*QueryListRoundsRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{23}
}

type QueryListRoundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        []*VoteRound           `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListRoundsResponse) Reset() {
	*x = QueryListRoundsResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListRoundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListRoundsResponse) ProtoMessage() {}

func (x *QueryListRoundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListRoundsResponse.ProtoReflect.Descriptor instead.
func (*QueryListRoundsResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{24}
}

func (x *QueryListRoundsResponse) GetRounds() []*VoteRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

type QueryPallasKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPallasKeysRequest) Reset() {
	*x = QueryPallasKeysRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPallasKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPallasKeysRequest) ProtoMessage() {}

func (x *QueryPallasKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPallasKeysRequest.ProtoReflect.Descriptor instead.
func (*QueryPallasKeysRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{25}
}

type QueryPallasKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*ValidatorPallasKey  `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPallasKeysResponse) Reset() {
	*x = QueryPallasKeysResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPallasKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPallasKeysResponse) ProtoMessage() {}

func (x *QueryPallasKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPallasKeysResponse.ProtoReflect.Descriptor instead.
func (*QueryPallasKeysResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{26}
}

func (x *QueryPallasKeysResponse) GetValidators() []*ValidatorPallasKey {
	if x != nil {
		return x.Validators
	}
	return nil
}

type QueryEndorsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEndorsersRequest) Reset() {
	*x = QueryEndorsersRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEndorsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEndorsersRequest) ProtoMessage() {}

func (x *QueryEndorsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEndorsersRequest.ProtoReflect.Descriptor instead.
func (*QueryEndorsersRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{27}
}

type QueryEndorsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endorsers     []*Endorser            `protobuf:"bytes,1,rep,name=endorsers,proto3" json:"endorsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEndorsersResponse) Reset() {
	*x = QueryEndorsersResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEndorsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEndorsersResponse) ProtoMessage() {}

func (x *QueryEndorsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEndorsersResponse.ProtoReflect.Descriptor instead.
func (*QueryEndorsersResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{28}
}

func (x *QueryEndorsersResponse) GetEndorsers() []*Endorser {
	if x != nil {
		return x.Endorsers
	}
	return nil
}

type QueryEndorsedRoundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndorserId    string                 `protobuf:"bytes,1,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEndorsedRoundsRequest) Reset() {
	*x = QueryEndorsedRoundsRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEndorsedRoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEndorsedRoundsRequest) ProtoMessage() {}

func (x *QueryEndorsedRoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEndorsedRoundsRequest.ProtoReflect.Descriptor instead.
func (*QueryEndorsedRoundsRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{29}
}

func (x *QueryEndorsedRoundsRequest) GetEndorserId() string {
	if x != nil {
		return x.EndorserId
	}
	return ""
}

type QueryEndorsedRoundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundIds  [][]byte               `protobuf:"bytes,1,rep,name=vote_round_ids,json=voteRoundIds,proto3" json:"vote_round_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEndorsedRoundsResponse) Reset() {
	*x = QueryEndorsedRoundsResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEndorsedRoundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEndorsedRoundsResponse) ProtoMessage() {}

func (x *QueryEndorsedRoundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEndorsedRoundsResponse.ProtoReflect.Descriptor instead.
func (*QueryEndorsedRoundsResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{30}
}

func (x *QueryEndorsedRoundsResponse) GetVoteRoundIds() [][]byte {
	if x != nil {
		return x.VoteRoundIds
	}
	return nil
}

type QueryCoordinatorActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCoordinatorActionRequest) Reset() {
	*x = QueryCoordinatorActionRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCoordinatorActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCoordinatorActionRequest) ProtoMessage() {}

func (x *QueryCoordinatorActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCoordinatorActionRequest.ProtoReflect.Descriptor instead.
func (*QueryCoordinatorActionRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{31}
}

func (x *QueryCoordinatorActionRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

type QueryCoordinatorActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *CoordinatorAction     `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCoordinatorActionResponse) Reset() {
	*x = QueryCoordinatorActionResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCoordinatorActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCoordinatorActionResponse) ProtoMessage() {}

func (x *QueryCoordinatorActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCoordinatorActionResponse.ProtoReflect.Descriptor instead.
func (*QueryCoordinatorActionResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{32}
}

func (x *QueryCoordinatorActionResponse) GetAction() *CoordinatorAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type QueryPendingCoordinatorActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPendingCoordinatorActionsRequest) Reset() {
	*x = QueryPendingCoordinatorActionsRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingCoordinatorActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingCoordinatorActionsRequest) ProtoMessage() {}

func (x *QueryPendingCoordinatorActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingCoordinatorActionsRequest.ProtoReflect.Descriptor instead.
func (*QueryPendingCoordinatorActionsRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{33}
}

type QueryPendingCoordinatorActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*CoordinatorAction   `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPendingCoordinatorActionsResponse) Reset() {
	*x = QueryPendingCoordinatorActionsResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingCoordinatorActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingCoordinatorActionsResponse) ProtoMessage() {}

func (x *QueryPendingCoordinatorActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingCoordinatorActionsResponse.ProtoReflect.Descriptor instead.
func (*QueryPendingCoordinatorActionsResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{34}
}

func (x *QueryPendingCoordinatorActionsResponse) GetActions() []*CoordinatorAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type QueryRoundOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoundOverviewRequest) Reset() {
	*x = QueryRoundOverviewRequest{}
	mi := &file_svote_v1_query_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoundOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoundOverviewRequest) ProtoMessage() {}

func (x *QueryRoundOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoundOverviewRequest.ProtoReflect.Descriptor instead.
func (*QueryRoundOverviewRequest) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{35}
}

type QueryRoundOverviewResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentRounds       []*VoteRound           `protobuf:"bytes,1,rep,name=current_rounds,json=currentRounds,proto3" json:"current_rounds,omitempty"`
	CompletedRoundCount uint64                 `protobuf:"varint,2,opt,name=completed_round_count,json=completedRoundCount,proto3" json:"completed_round_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryRoundOverviewResponse) Reset() {
	*x = QueryRoundOverviewResponse{}
	mi := &file_svote_v1_query_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoundOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoundOverviewResponse) ProtoMessage() {}

func (x *QueryRoundOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_query_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoundOverviewResponse.ProtoReflect.Descriptor instead.
func (*QueryRoundOverviewResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_query_proto_rawDescGZIP(), []int{36}
}

func (x *QueryRoundOverviewResponse) GetCurrentRounds() []*VoteRound {
	if x != nil {
		return x.CurrentRounds
	}
	return nil
}

func (x *QueryRoundOverviewResponse) GetCompletedRoundCount() uint64 {
	if x != nil {
		return x.CompletedRoundCount
	}
	return 0
}

var File_svote_v1_query_proto protoreflect.FileDescriptor

const file_svote_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14svote/v1/query.proto\x12\bsvote.v1\x1a\x14svote/v1/types.proto\"X\n" +
	"\x1aQueryCommitmentTreeRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\"\n" +
	"\rvote_round_id\x18\x02 \x01(\fR\vvoteRoundId\"P\n" +
	"\x1bQueryCommitmentTreeResponse\x121\n" +
	"\x04tree\x18\x01 \x01(\v2\x1d.svote.v1.CommitmentTreeStateR\x04tree\"<\n" +
	"\x16QueryLatestTreeRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"L\n" +
	"\x17QueryLatestTreeResponse\x121\n" +
	"\x04tree\x18\x01 \x01(\v2\x1d.svote.v1.CommitmentTreeStateR\x04tree\";\n" +
	"\x15QueryVoteRoundRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"C\n" +
	"\x16QueryVoteRoundResponse\x12)\n" +
	"\x05round\x18\x01 \x01(\v2\x13.svote.v1.VoteRoundR\x05round\"`\n" +
	"\x19QueryProposalTallyRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\"\x9d\x01\n" +
	"\x1aQueryProposalTallyResponse\x12E\n" +
	"\x05tally\x18\x01 \x03(\v2/.svote.v1.QueryProposalTallyResponse.TallyEntryR\x05tally\x1a8\n" +
	"\n" +
	"TallyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\">\n" +
	"\x18QueryTallyResultsRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"L\n" +
	"\x19QueryTallyResultsResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.svote.v1.TallyResultR\aresults\"D\n" +
	"\x1eQueryPartialDecryptionsRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"^\n" +
	"\x1fQueryPartialDecryptionsResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.svote.v1.StoredPartialDecryptionR\aentries\"\xd0\x01\n" +
	"\x17StoredPartialDecryption\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\rR\x0evalidatorIndex\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12'\n" +
	"\x0fpartial_decrypt\x18\x04 \x01(\fR\x0epartialDecrypt\x12\x1d\n" +
	"\n" +
	"dleq_proof\x18\x05 \x01(\fR\tdleqProof\"\x80\x01\n" +
	"\x1cQueryCommitmentLeavesRequest\x12\x1f\n" +
	"\vfrom_height\x18\x01 \x01(\x04R\n" +
	"fromHeight\x12\x1b\n" +
	"\tto_height\x18\x02 \x01(\x04R\btoHeight\x12\"\n" +
	"\rvote_round_id\x18\x03 \x01(\fR\vvoteRoundId\"}\n" +
	"\x1dQueryCommitmentLeavesResponse\x122\n" +
	"\x06blocks\x18\x01 \x03(\v2\x1a.svote.v1.BlockCommitmentsR\x06blocks\x12(\n" +
	"\x10next_from_height\x18\x02 \x01(\x04R\x0enextFromHeight\"\x19\n" +
	"\x17QueryActiveRoundRequest\"E\n" +
	"\x18QueryActiveRoundResponse\x12)\n" +
	"\x05round\x18\x01 \x01(\v2\x13.svote.v1.VoteRoundR\x05round\"\x1b\n" +
	"\x19QueryCeremonyStateRequest\"Q\n" +
	"\x1aQueryCeremonyStateResponse\x123\n" +
	"\bceremony\x18\x01 \x01(\v2\x17.svote.v1.CeremonyStateR\bceremony\"\x1a\n" +
	"\x18QueryVoteManagersRequest\"\xa7\x01\n" +
	"\x19QueryVoteManagersResponse\x124\n" +
	"\x16vote_manager_addresses\x18\x01 \x03(\tR\x14voteManagerAddresses\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\rR\tthreshold\x126\n" +
	"\x17min_ceremony_validators\x18\x03 \x01(\rR\x15minCeremonyValidators\"=\n" +
	"\x17QueryVoteSummaryRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"\xee\x01\n" +
	"\x18QueryVoteSummaryResponse\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.svote.v1.SessionStatusR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\rvote_end_time\x18\x04 \x01(\x04R\vvoteEndTime\x127\n" +
	"\tproposals\x18\x05 \x03(\v2\x19.svote.v1.ProposalSummaryR\tproposals\"\x18\n" +
	"\x16QueryListRoundsRequest\"F\n" +
	"\x17QueryListRoundsResponse\x12+\n" +
	"\x06rounds\x18\x01 \x03(\v2\x13.svote.v1.VoteRoundR\x06rounds\"\x18\n" +
	"\x16QueryPallasKeysRequest\"W\n" +
	"\x17QueryPallasKeysResponse\x12<\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x1c.svote.v1.ValidatorPallasKeyR\n" +
	"validators\"\x17\n" +
	"\x15QueryEndorsersRequest\"J\n" +
	"\x16QueryEndorsersResponse\x120\n" +
	"\tendorsers\x18\x01 \x03(\v2\x12.svote.v1.EndorserR\tendorsers\"=\n" +
	"\x1aQueryEndorsedRoundsRequest\x12\x1f\n" +
	"\vendorser_id\x18\x01 \x01(\tR\n" +
	"endorserId\"C\n" +
	"\x1bQueryEndorsedRoundsResponse\x12$\n" +
	"\x0evote_round_ids\x18\x01 \x03(\fR\fvoteRoundIds\"<\n" +
	"\x1dQueryCoordinatorActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\"U\n" +
	"\x1eQueryCoordinatorActionResponse\x123\n" +
	"\x06action\x18\x01 \x01(\v2\x1b.svote.v1.CoordinatorActionR\x06action\"'\n" +
	"%QueryPendingCoordinatorActionsRequest\"_\n" +
	"&QueryPendingCoordinatorActionsResponse\x125\n" +
	"\aactions\x18\x01 \x03(\v2\x1b.svote.v1.CoordinatorActionR\aactions\"\x1b\n" +
	"\x19QueryRoundOverviewRequest\"\x8c\x01\n" +
	"\x1aQueryRoundOverviewResponse\x12:\n" +
	"\x0ecurrent_rounds\x18\x01 \x03(\v2\x13.svote.v1.VoteRoundR\rcurrentRounds\x122\n" +
	"\x15completed_round_count\x18\x02 \x01(\x04R\x13completedRoundCount2\x9a\r\n" +
	"\x05Query\x12e\n" +
	"\x16CommitmentTreeAtHeight\x12$.svote.v1.QueryCommitmentTreeRequest\x1a%.svote.v1.QueryCommitmentTreeResponse\x12[\n" +
	"\x14LatestCommitmentTree\x12 .svote.v1.QueryLatestTreeRequest\x1a!.svote.v1.QueryLatestTreeResponse\x12N\n" +
	"\tVoteRound\x12\x1f.svote.v1.QueryVoteRoundRequest\x1a .svote.v1.QueryVoteRoundResponse\x12Z\n" +
	"\rProposalTally\x12#.svote.v1.QueryProposalTallyRequest\x1a$.svote.v1.QueryProposalTallyResponse\x12W\n" +
	"\fTallyResults\x12\".svote.v1.QueryTallyResultsRequest\x1a#.svote.v1.QueryTallyResultsResponse\x12i\n" +
	"\x12PartialDecryptions\x12(.svote.v1.QueryPartialDecryptionsRequest\x1a).svote.v1.QueryPartialDecryptionsResponse\x12c\n" +
	"\x10CommitmentLeaves\x12&.svote.v1.QueryCommitmentLeavesRequest\x1a'.svote.v1.QueryCommitmentLeavesResponse\x12T\n" +
	"\vActiveRound\x12!.svote.v1.QueryActiveRoundRequest\x1a\".svote.v1.QueryActiveRoundResponse\x12Z\n" +
	"\rCeremonyState\x12#.svote.v1.QueryCeremonyStateRequest\x1a$.svote.v1.QueryCeremonyStateResponse\x12W\n" +
	"\fVoteManagers\x12\".svote.v1.QueryVoteManagersRequest\x1a#.svote.v1.QueryVoteManagersResponse\x12T\n" +
	"\vVoteSummary\x12!.svote.v1.QueryVoteSummaryRequest\x1a\".svote.v1.QueryVoteSummaryResponse\x12Q\n" +
	"\n" +
	"ListRounds\x12 .svote.v1.QueryListRoundsRequest\x1a!.svote.v1.QueryListRoundsResponse\x12Q\n" +
	"\n" +
	"PallasKeys\x12 .svote.v1.QueryPallasKeysRequest\x1a!.svote.v1.QueryPallasKeysResponse\x12N\n" +
	"\tEndorsers\x12\x1f.svote.v1.QueryEndorsersRequest\x1a .svote.v1.QueryEndorsersResponse\x12]\n" +
	"\x0eEndorsedRounds\x12$.svote.v1.QueryEndorsedRoundsRequest\x1a%.svote.v1.QueryEndorsedRoundsResponse\x12f\n" +
	"\x11CoordinatorAction\x12'.svote.v1.QueryCoordinatorActionRequest\x1a(.svote.v1.QueryCoordinatorActionResponse\x12~\n" +
	"\x19PendingCoordinatorActions\x12/.svote.v1.QueryPendingCoordinatorActionsRequest\x1a0.svote.v1.QueryPendingCoordinatorActionsResponse\x12Z\n" +
	"\rRoundOverview\x12#.svote.v1.QueryRoundOverviewRequest\x1a$.svote.v1.QueryRoundOverviewResponseB-Z+github.com/valargroup/vote-sdk/x/vote/typesb\x06proto3"

var (
	file_svote_v1_query_proto_rawDescOnce sync.Once
	file_svote_v1_query_proto_rawDescData []byte
)

func file_svote_v1_query_proto_rawDescGZIP() []byte {
	file_svote_v1_query_proto_rawDescOnce.Do(func() {
		file_svote_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svote_v1_query_proto_rawDesc), len(file_svote_v1_query_proto_rawDesc)))
	})
	return file_svote_v1_query_proto_rawDescData
}

var file_svote_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_svote_v1_query_proto_goTypes = []any{
	(*QueryCommitmentTreeRequest)(nil),             // 0: svote.v1.QueryCommitmentTreeRequest
	(*QueryCommitmentTreeResponse)(nil),            // 1: svote.v1.QueryCommitmentTreeResponse
	(*QueryLatestTreeRequest)(nil),                 // 2: svote.v1.QueryLatestTreeRequest
	(*QueryLatestTreeResponse)(nil),                // 3: svote.v1.QueryLatestTreeResponse
	(*QueryVoteRoundRequest)(nil),                  // 4: svote.v1.QueryVoteRoundRequest
	(*QueryVoteRoundResponse)(nil),                 // 5: svote.v1.QueryVoteRoundResponse
	(*QueryProposalTallyRequest)(nil),              // 6: svote.v1.QueryProposalTallyRequest
	(*QueryProposalTallyResponse)(nil),             // 7: svote.v1.QueryProposalTallyResponse
	(*QueryTallyResultsRequest)(nil),               // 8: svote.v1.QueryTallyResultsRequest
	(*QueryTallyResultsResponse)(nil),              // 9: svote.v1.QueryTallyResultsResponse
	(*QueryPartialDecryptionsRequest)(nil),         // 10: svote.v1.QueryPartialDecryptionsRequest
	(*QueryPartialDecryptionsResponse)(nil),        // 11: svote.v1.QueryPartialDecryptionsResponse
	(*StoredPartialDecryption)(nil),                // 12: svote.v1.StoredPartialDecryption
	(*QueryCommitmentLeavesRequest)(nil),           // 13: svote.v1.QueryCommitmentLeavesRequest
	(*QueryCommitmentLeavesResponse)(nil),          // 14: svote.v1.QueryCommitmentLeavesResponse
	(*QueryActiveRoundRequest)(nil),                // 15: svote.v1.QueryActiveRoundRequest
	(*QueryActiveRoundResponse)(nil),               // 16: svote.v1.QueryActiveRoundResponse
	(*QueryCeremonyStateRequest)(nil),              // 17: svote.v1.QueryCeremonyStateRequest
	(*QueryCeremonyStateResponse)(nil),             // 18: svote.v1.QueryCeremonyStateResponse
	(*QueryVoteManagersRequest)(nil),               // 19: svote.v1.QueryVoteManagersRequest
	(*QueryVoteManagersResponse)(nil),              // 20: svote.v1.QueryVoteManagersResponse
	(*QueryVoteSummaryRequest)(nil),                // 21: svote.v1.QueryVoteSummaryRequest
	(*QueryVoteSummaryResponse)(nil),               // 22: svote.v1.QueryVoteSummaryResponse
	(*QueryListRoundsRequest)(nil),                 // 23: svote.v1.QueryListRoundsRequest
	(*QueryListRoundsResponse)(nil),                // 24: svote.v1.QueryListRoundsResponse
	(*QueryPallasKeysRequest)(nil),                 // 25: svote.v1.QueryPallasKeysRequest
	(*QueryPallasKeysResponse)(nil),                // 26: svote.v1.QueryPallasKeysResponse
	(*QueryEndorsersRequest)(nil),                  // 27: svote.v1.QueryEndorsersRequest
	(*QueryEndorsersResponse)(nil),                 // 28: svote.v1.QueryEndorsersResponse
	(*QueryEndorsedRoundsRequest)(nil),             // 29: svote.v1.QueryEndorsedRoundsRequest
	(*QueryEndorsedRoundsResponse)(nil),            // 30: svote.v1.QueryEndorsedRoundsResponse
	(*QueryCoordinatorActionRequest)(nil),          // 31: svote.v1.QueryCoordinatorActionRequest
	(*QueryCoordinatorActionResponse)(nil),         // 32: svote.v1.QueryCoordinatorActionResponse
	(*QueryPendingCoordinatorActionsRequest)(nil),  // 33: svote.v1.QueryPendingCoordinatorActionsRequest
	(*QueryPendingCoordinatorActionsResponse)(nil), // 34: svote.v1.QueryPendingCoordinatorActionsResponse
	(*QueryRoundOverviewRequest)(nil),              // 35: svote.v1.QueryRoundOverviewRequest
	(*QueryRoundOverviewResponse)(nil),             // 36: svote.v1.QueryRoundOverviewResponse
	nil,                                            // 37: svote.v1.QueryProposalTallyResponse.TallyEntry
	(*CommitmentTreeState)(nil),                    // 38: svote.v1.CommitmentTreeState
	(*VoteRound)(nil),                              // 39: svote.v1.VoteRound
	(*TallyResult)(nil),                            // 40: svote.v1.TallyResult
	(*BlockCommitments)(nil),                       // 41: svote.v1.BlockCommitments
	(*CeremonyState)(nil),                          // 42: svote.v1.CeremonyState
	(SessionStatus)(0),                             // 43: svote.v1.SessionStatus
	(*ProposalSummary)(nil),                        // 44: svote.v1.ProposalSummary
	(*ValidatorPallasKey)(nil),                     // 45: svote.v1.ValidatorPallasKey
	(*Endorser)(nil),                               // 46: svote.v1.Endorser
	(*CoordinatorAction)(nil),                      // 47: svote.v1.CoordinatorAction
}
var file_svote_v1_query_proto_depIdxs = []int32{
	38, // 0: svote.v1.QueryCommitmentTreeResponse.tree:type_name -> svote.v1.CommitmentTreeState
	38, // 1: svote.v1.QueryLatestTreeResponse.tree:type_name -> svote.v1.CommitmentTreeState
	39, // 2: svote.v1.QueryVoteRoundResponse.round:type_name -> svote.v1.VoteRound
	37, // 3: svote.v1.QueryProposalTallyResponse.tally:type_name -> svote.v1.QueryProposalTallyResponse.TallyEntry
	40, // 4: svote.v1.QueryTallyResultsResponse.results:type_name -> svote.v1.TallyResult
	12, // 5: svote.v1.QueryPartialDecryptionsResponse.entries:type_name -> svote.v1.StoredPartialDecryption
	41, // 6: svote.v1.QueryCommitmentLeavesResponse.blocks:type_name -> svote.v1.BlockCommitments
	39, // 7: svote.v1.QueryActiveRoundResponse.round:type_name -> svote.v1.VoteRound
	42, // 8: svote.v1.QueryCeremonyStateResponse.ceremony:type_name -> svote.v1.CeremonyState
	43, // 9: svote.v1.QueryVoteSummaryResponse.status:type_name -> svote.v1.SessionStatus
	44, // 10: svote.v1.QueryVoteSummaryResponse.proposals:type_name -> svote.v1.ProposalSummary
	39, // 11: svote.v1.QueryListRoundsResponse.rounds:type_name -> svote.v1.VoteRound
	45, // 12: svote.v1.QueryPallasKeysResponse.validators:type_name -> svote.v1.ValidatorPallasKey
	46, // 13: svote.v1.QueryEndorsersResponse.endorsers:type_name -> svote.v1.Endorser
	47, // 14: svote.v1.QueryCoordinatorActionResponse.action:type_name -> svote.v1.CoordinatorAction
	47, // 15: svote.v1.QueryPendingCoordinatorActionsResponse.actions:type_name -> svote.v1.CoordinatorAction
	39, // 16: svote.v1.QueryRoundOverviewResponse.current_rounds:type_name -> svote.v1.VoteRound
	0,  // 17: svote.v1.Query.CommitmentTreeAtHeight:input_type -> svote.v1.QueryCommitmentTreeRequest
	2,  // 18: svote.v1.Query.LatestCommitmentTree:input_type -> svote.v1.QueryLatestTreeRequest
	4,  // 19: svote.v1.Query.VoteRound:input_type -> svote.v1.QueryVoteRoundRequest
	6,  // 20: svote.v1.Query.ProposalTally:input_type -> svote.v1.QueryProposalTallyRequest
	8,  // 21: svote.v1.Query.TallyResults:input_type -> svote.v1.QueryTallyResultsRequest
	10, // 22: svote.v1.Query.PartialDecryptions:input_type -> svote.v1.QueryPartialDecryptionsRequest
	13, // 23: svote.v1.Query.CommitmentLeaves:input_type -> svote.v1.QueryCommitmentLeavesRequest
	15, // 24: svote.v1.Query.ActiveRound:input_type -> svote.v1.QueryActiveRoundRequest
	17, // 25: svote.v1.Query.CeremonyState:input_type -> svote.v1.QueryCeremonyStateRequest
	19, // 26: svote.v1.Query.VoteManagers:input_type -> svote.v1.QueryVoteManagersRequest
	21, // 27: svote.v1.Query.VoteSummary:input_type -> svote.v1.QueryVoteSummaryRequest
	23, // 28: svote.v1.Query.ListRounds:input_type -> svote.v1.QueryListRoundsRequest
	25, // 29: svote.v1.Query.PallasKeys:input_type -> svote.v1.QueryPallasKeysRequest
	27, // 30: svote.v1.Query.Endorsers:input_type -> svote.v1.QueryEndorsersRequest
	29, // 31: svote.v1.Query.EndorsedRounds:input_type -> svote.v1.QueryEndorsedRoundsRequest
	31, // 32: svote.v1.Query.CoordinatorAction:input_type -> svote.v1.QueryCoordinatorActionRequest
	33, // 33: svote.v1.Query.PendingCoordinatorActions:input_type -> svote.v1.QueryPendingCoordinatorActionsRequest
	35, // 34: svote.v1.Query.RoundOverview:input_type -> svote.v1.QueryRoundOverviewRequest
	1,  // 35: svote.v1.Query.CommitmentTreeAtHeight:output_type -> svote.v1.QueryCommitmentTreeResponse
	3,  // 36: svote.v1.Query.LatestCommitmentTree:output_type -> svote.v1.QueryLatestTreeResponse
	5,  // 37: svote.v1.Query.VoteRound:output_type -> svote.v1.QueryVoteRoundResponse
	7,  // 38: svote.v1.Query.ProposalTally:output_type -> svote.v1.QueryProposalTallyResponse
	9,  // 39: svote.v1.Query.TallyResults:output_type -> svote.v1.QueryTallyResultsResponse
	11, // 40: svote.v1.Query.PartialDecryptions:output_type -> svote.v1.QueryPartialDecryptionsResponse
	14, // 41: svote.v1.Query.CommitmentLeaves:output_type -> svote.v1.QueryCommitmentLeavesResponse
	16, // 42: svote.v1.Query.ActiveRound:output_type -> svote.v1.QueryActiveRoundResponse
	18, // 43: svote.v1.Query.CeremonyState:output_type -> svote.v1.QueryCeremonyStateResponse
	20, // 44: svote.v1.Query.VoteManagers:output_type -> svote.v1.QueryVoteManagersResponse
	22, // 45: svote.v1.Query.VoteSummary:output_type -> svote.v1.QueryVoteSummaryResponse
	24, // 46: svote.v1.Query.ListRounds:output_type -> svote.v1.QueryListRoundsResponse
	26, // 47: svote.v1.Query.PallasKeys:output_type -> svote.v1.QueryPallasKeysResponse
	28, // 48: svote.v1.Query.Endorsers:output_type -> svote.v1.QueryEndorsersResponse
	30, // 49: svote.v1.Query.EndorsedRounds:output_type -> svote.v1.QueryEndorsedRoundsResponse
	32, // 50: svote.v1.Query.CoordinatorAction:output_type -> svote.v1.QueryCoordinatorActionResponse
	34, // 51: svote.v1.Query.PendingCoordinatorActions:output_type -> svote.v1.QueryPendingCoordinatorActionsResponse
	36, // 52: svote.v1.Query.RoundOverview:output_type -> svote.v1.QueryRoundOverviewResponse
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_svote_v1_query_proto_init() }
func file_svote_v1_query_proto_init() {
	if File_svote_v1_query_proto != nil {
		return
	}
	file_svote_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svote_v1_query_proto_rawDesc), len(file_svote_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svote_v1_query_proto_goTypes,
		DependencyIndexes: file_svote_v1_query_proto_depIdxs,
		MessageInfos:      file_svote_v1_query_proto_msgTypes,
	}.Build()
	File_svote_v1_query_proto = out.File
	file_svote_v1_query_proto_goTypes = nil
	file_svote_v1_query_proto_depIdxs = nil
}
