// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: svote/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateVotingSession creates a new voting session.
// vote_round_id is computed on-chain as Poseidon(created_at_height, snapshot_blockhash_lo, snapshot_blockhash_hi, proposals_hash_lo, proposals_hash_hi, vote_end_time, nullifier_imt_root, nc_root).
// The output is a canonical 32-byte Pallas Fp element. Creates the round in
// PENDING status; ea_pk is set when the per-round ceremony confirms.
type MsgCreateVotingSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Creator           string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	Proposals         []*Proposal            `protobuf:"bytes,8,rep,name=proposals,proto3" json:"proposals,omitempty"`
	Description       string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`                           // Human-readable round description
	Title             string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`                                      // Short human-readable round title
	DiscussionUrl     string                 `protobuf:"bytes,11,opt,name=discussion_url,json=discussionUrl,proto3" json:"discussion_url,omitempty"` // Overall forum discussion link for the vote round
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgCreateVotingSession) Reset() {
	*x = MsgCreateVotingSession{}
	mi := &file_svote_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSession) ProtoMessage() {}

func (x *MsgCreateVotingSession) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSession.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSession) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateVotingSession) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateVotingSession) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *MsgCreateVotingSession) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *MsgCreateVotingSession) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *MsgCreateVotingSession) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MsgCreateVotingSession) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MsgCreateVotingSession) GetDiscussionUrl() string {
	if x != nil {
		return x.DiscussionUrl
	}
	return ""
}

type MsgCreateVotingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateVotingSessionResponse) Reset() {
	*x = MsgCreateVotingSessionResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSessionResponse) ProtoMessage() {}

func (x *MsgCreateVotingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSessionResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSessionResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateVotingSessionResponse) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

// MsgDelegateVote corresponds to ZKP #1: delegation registration from keystone-signed action.
type MsgDelegateVote struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Rk                  []byte                 `protobuf:"bytes,1,opt,name=rk,proto3" json:"rk,omitempty"`                                                                // Randomized spend auth key (32 bytes)
	SpendAuthSig        []byte                 `protobuf:"bytes,2,opt,name=spend_auth_sig,json=spendAuthSig,proto3" json:"spend_auth_sig,omitempty"`                      // RedPallas signature
	SignedNoteNullifier []byte                 `protobuf:"bytes,3,opt,name=signed_note_nullifier,json=signedNoteNullifier,proto3" json:"signed_note_nullifier,omitempty"` // Nullifier of the dummy signed note
	CmxNew              []byte                 `protobuf:"bytes,4,opt,name=cmx_new,json=cmxNew,proto3" json:"cmx_new,omitempty"`                                          // Output note commitment
	VanCmx              []byte                 `protobuf:"bytes,6,opt,name=van_cmx,json=vanCmx,proto3" json:"van_cmx,omitempty"`                                          // Vote authority note commitment
	GovNullifiers       [][]byte               `protobuf:"bytes,7,rep,name=gov_nullifiers,json=govNullifiers,proto3" json:"gov_nullifiers,omitempty"`                     // Up to 5 governance nullifiers
	Proof               []byte                 `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`                                                          // Halo2 ZKP #1
	VoteRoundId         []byte                 `protobuf:"bytes,9,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Sighash             []byte                 `protobuf:"bytes,10,opt,name=sighash,proto3" json:"sighash,omitempty"` // Client-provided sighash for RedPallas signature verification (32 bytes)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgDelegateVote) Reset() {
	*x = MsgDelegateVote{}
	mi := &file_svote_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVote) ProtoMessage() {}

func (x *MsgDelegateVote) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVote.ProtoReflect.Descriptor instead.
func (*MsgDelegateVote) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDelegateVote) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *MsgDelegateVote) GetSpendAuthSig() []byte {
	if x != nil {
		return x.SpendAuthSig
	}
	return nil
}

func (x *MsgDelegateVote) GetSignedNoteNullifier() []byte {
	if x != nil {
		return x.SignedNoteNullifier
	}
	return nil
}

func (x *MsgDelegateVote) GetCmxNew() []byte {
	if x != nil {
		return x.CmxNew
	}
	return nil
}

func (x *MsgDelegateVote) GetVanCmx() []byte {
	if x != nil {
		return x.VanCmx
	}
	return nil
}

func (x *MsgDelegateVote) GetGovNullifiers() [][]byte {
	if x != nil {
		return x.GovNullifiers
	}
	return nil
}

func (x *MsgDelegateVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgDelegateVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgDelegateVote) GetSighash() []byte {
	if x != nil {
		return x.Sighash
	}
	return nil
}

type MsgDelegateVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDelegateVoteResponse) Reset() {
	*x = MsgDelegateVoteResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVoteResponse) ProtoMessage() {}

func (x *MsgDelegateVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgDelegateVoteResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgCastVote corresponds to ZKP #2: create a vote commitment.
// Condition 4 (Spend Authority) adds r_vpk = vsk.ak + [alpha_v]*G; the circuit
// exposes r_vpk_x and r_vpk_y as public inputs, so the client must send them.
type MsgCastVote struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VanNullifier             []byte                 `protobuf:"bytes,1,opt,name=van_nullifier,json=vanNullifier,proto3" json:"van_nullifier,omitempty"`
	VoteAuthorityNoteNew     []byte                 `protobuf:"bytes,2,opt,name=vote_authority_note_new,json=voteAuthorityNoteNew,proto3" json:"vote_authority_note_new,omitempty"`
	VoteCommitment           []byte                 `protobuf:"bytes,3,opt,name=vote_commitment,json=voteCommitment,proto3" json:"vote_commitment,omitempty"`
	ProposalId               uint32                 `protobuf:"varint,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	// Fields 8-9 removed: r_vpk_x/r_vpk_y are now decompressed from r_vpk in the FFI verifier.
	VoteAuthSig []byte `protobuf:"bytes,10,opt,name=vote_auth_sig,json=voteAuthSig,proto3" json:"vote_auth_sig,omitempty"` // RedPallas signature under randomized voting key
	// Field 11 removed: sighash is now computed on-chain via ComputeCastVoteSighash.
	RVpk          []byte `protobuf:"bytes,12,opt,name=r_vpk,json=rVpk,proto3" json:"r_vpk,omitempty"` // Compressed Pallas point (32 bytes) — sig verification + FFI decompresses to (x,y) for ZKP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCastVote) Reset() {
	*x = MsgCastVote{}
	mi := &file_svote_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVote) ProtoMessage() {}

func (x *MsgCastVote) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVote.ProtoReflect.Descriptor instead.
func (*MsgCastVote) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgCastVote) GetVanNullifier() []byte {
	if x != nil {
		return x.VanNullifier
	}
	return nil
}

func (x *MsgCastVote) GetVoteAuthorityNoteNew() []byte {
	if x != nil {
		return x.VoteAuthorityNoteNew
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommitment() []byte {
	if x != nil {
		return x.VoteCommitment
	}
	return nil
}

func (x *MsgCastVote) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgCastVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgCastVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

func (x *MsgCastVote) GetVoteAuthSig() []byte {
	if x != nil {
		return x.VoteAuthSig
	}
	return nil
}

func (x *MsgCastVote) GetRVpk() []byte {
	if x != nil {
		return x.RVpk
	}
	return nil
}

type MsgCastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCastVoteResponse) Reset() {
	*x = MsgCastVoteResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVoteResponse) ProtoMessage() {}

func (x *MsgCastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgCastVoteResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{5}
}

// MsgRevealShare corresponds to ZKP #3: reveal vote share (server submits).
type MsgRevealShare struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ShareNullifier           []byte                 `protobuf:"bytes,1,opt,name=share_nullifier,json=shareNullifier,proto3" json:"share_nullifier,omitempty"`
	EncShare                 []byte                 `protobuf:"bytes,2,opt,name=enc_share,json=encShare,proto3" json:"enc_share,omitempty"` // 64 bytes: ElGamal ciphertext (C1 || C2, compressed Pallas points)
	ProposalId               uint32                 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision             uint32                 `protobuf:"varint,4,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgRevealShare) Reset() {
	*x = MsgRevealShare{}
	mi := &file_svote_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShare) ProtoMessage() {}

func (x *MsgRevealShare) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShare.ProtoReflect.Descriptor instead.
func (*MsgRevealShare) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRevealShare) GetShareNullifier() []byte {
	if x != nil {
		return x.ShareNullifier
	}
	return nil
}

func (x *MsgRevealShare) GetEncShare() []byte {
	if x != nil {
		return x.EncShare
	}
	return nil
}

func (x *MsgRevealShare) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgRevealShare) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *MsgRevealShare) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgRevealShare) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgRevealShare) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgRevealShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealShareResponse) Reset() {
	*x = MsgRevealShareResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShareResponse) ProtoMessage() {}

func (x *MsgRevealShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShareResponse.ProtoReflect.Descriptor instead.
func (*MsgRevealShareResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{7}
}

// MsgSubmitTally finalizes a voting session, transitioning it from TALLYING to FINALIZED.
// The election authority submits decrypted vote totals for each (proposal, decision) pair.
// Only the session creator (election authority) may submit this message.
type MsgSubmitTally struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Creator       string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"` // Must match the session creator
	Entries       []*TallyEntry          `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"` // One per (proposal_id, vote_decision) pair
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitTally) Reset() {
	*x = MsgSubmitTally{}
	mi := &file_svote_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTally) ProtoMessage() {}

func (x *MsgSubmitTally) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTally.ProtoReflect.Descriptor instead.
func (*MsgSubmitTally) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgSubmitTally) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgSubmitTally) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSubmitTally) GetEntries() []*TallyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// TallyEntry contains the decrypted vote total for one (proposal, decision) pair.
type TallyEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      uint32                 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision    uint32                 `protobuf:"varint,2,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue      uint64                 `protobuf:"varint,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`               // Decrypted aggregate (zatoshi)
	DecryptionProof []byte                 `protobuf:"bytes,4,opt,name=decryption_proof,json=decryptionProof,proto3" json:"decryption_proof,omitempty"` // Chaum-Pedersen DLEQ proof (reserved for future use)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TallyEntry) Reset() {
	*x = TallyEntry{}
	mi := &file_svote_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyEntry) ProtoMessage() {}

func (x *TallyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyEntry.ProtoReflect.Descriptor instead.
func (*TallyEntry) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *TallyEntry) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyEntry) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyEntry) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *TallyEntry) GetDecryptionProof() []byte {
	if x != nil {
		return x.DecryptionProof
	}
	return nil
}

type MsgSubmitTallyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinalizedEntries uint32                 `protobuf:"varint,1,opt,name=finalized_entries,json=finalizedEntries,proto3" json:"finalized_entries,omitempty"` // Number of tally entries stored
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgSubmitTallyResponse) Reset() {
	*x = MsgSubmitTallyResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTallyResponse) ProtoMessage() {}

func (x *MsgSubmitTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTallyResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitTallyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgSubmitTallyResponse) GetFinalizedEntries() uint32 {
	if x != nil {
		return x.FinalizedEntries
	}
	return 0
}

// MsgRegisterPallasKey registers a validator's Pallas public key for the EA key ceremony.
type MsgRegisterPallasKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                   // Validator address
	PallasPk      []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"` // Compressed Pallas point (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPallasKey) Reset() {
	*x = MsgRegisterPallasKey{}
	mi := &file_svote_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPallasKey) ProtoMessage() {}

func (x *MsgRegisterPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPallasKey.ProtoReflect.Descriptor instead.
func (*MsgRegisterPallasKey) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{11}
}

func (x *MsgRegisterPallasKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgRegisterPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

type MsgRegisterPallasKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPallasKeyResponse) Reset() {
	*x = MsgRegisterPallasKeyResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPallasKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPallasKeyResponse) ProtoMessage() {}

func (x *MsgRegisterPallasKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPallasKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterPallasKeyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{12}
}

// MsgRotatePallasKey replaces a validator's registered Pallas public key.
// Requires an existing registration and no in-flight ceremony for this validator.
type MsgRotatePallasKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                              // Validator account address (same as RegisterPallasKey)
	NewPallasPk   []byte                 `protobuf:"bytes,2,opt,name=new_pallas_pk,json=newPallasPk,proto3" json:"new_pallas_pk,omitempty"` // New compressed Pallas point (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRotatePallasKey) Reset() {
	*x = MsgRotatePallasKey{}
	mi := &file_svote_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRotatePallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRotatePallasKey) ProtoMessage() {}

func (x *MsgRotatePallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRotatePallasKey.ProtoReflect.Descriptor instead.
func (*MsgRotatePallasKey) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{13}
}

func (x *MsgRotatePallasKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgRotatePallasKey) GetNewPallasPk() []byte {
	if x != nil {
		return x.NewPallasPk
	}
	return nil
}

type MsgRotatePallasKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRotatePallasKeyResponse) Reset() {
	*x = MsgRotatePallasKeyResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRotatePallasKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRotatePallasKeyResponse) ProtoMessage() {}

func (x *MsgRotatePallasKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRotatePallasKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRotatePallasKeyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{14}
}

// MsgContributeDKG is a validator's contribution to the Joint-Feldman DKG.
// Each validator generates a random polynomial, publishes Feldman commitments,
// and distributes ECIES-encrypted shares to all ceremony participants.
type MsgContributeDKG struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Creator            string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	VoteRoundId        []byte                 `protobuf:"bytes,2,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	FeldmanCommitments [][]byte               `protobuf:"bytes,3,rep,name=feldman_commitments,json=feldmanCommitments,proto3" json:"feldman_commitments,omitempty"` // C_j = a_j*G for j=0..t-1
	Payloads           []*DealerPayload       `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`                                               // One ECIES envelope per ceremony validator
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MsgContributeDKG) Reset() {
	*x = MsgContributeDKG{}
	mi := &file_svote_v1_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgContributeDKG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContributeDKG) ProtoMessage() {}

func (x *MsgContributeDKG) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContributeDKG.ProtoReflect.Descriptor instead.
func (*MsgContributeDKG) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{15}
}

func (x *MsgContributeDKG) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgContributeDKG) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgContributeDKG) GetFeldmanCommitments() [][]byte {
	if x != nil {
		return x.FeldmanCommitments
	}
	return nil
}

func (x *MsgContributeDKG) GetPayloads() []*DealerPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type MsgContributeDKGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgContributeDKGResponse) Reset() {
	*x = MsgContributeDKGResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgContributeDKGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContributeDKGResponse) ProtoMessage() {}

func (x *MsgContributeDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContributeDKGResponse.ProtoReflect.Descriptor instead.
func (*MsgContributeDKGResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{16}
}

// MsgAckExecutiveAuthorityKey is submitted by a validator to acknowledge receipt of their ea_sk share.
type MsgAckExecutiveAuthorityKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                               // Validator address
	AckSignature  []byte                 `protobuf:"bytes,2,opt,name=ack_signature,json=ackSignature,proto3" json:"ack_signature,omitempty"` // Commitment digest: SHA256("ack" || ea_pk || validator_address). Not a cryptographic signature; field name kept for wire compatibility.
	VoteRoundId   []byte                 `protobuf:"bytes,3,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`  // Target voting round (per-round ceremony)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAckExecutiveAuthorityKey) Reset() {
	*x = MsgAckExecutiveAuthorityKey{}
	mi := &file_svote_v1_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAckExecutiveAuthorityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAckExecutiveAuthorityKey) ProtoMessage() {}

func (x *MsgAckExecutiveAuthorityKey) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAckExecutiveAuthorityKey.ProtoReflect.Descriptor instead.
func (*MsgAckExecutiveAuthorityKey) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{17}
}

func (x *MsgAckExecutiveAuthorityKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgAckExecutiveAuthorityKey) GetAckSignature() []byte {
	if x != nil {
		return x.AckSignature
	}
	return nil
}

func (x *MsgAckExecutiveAuthorityKey) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type MsgAckExecutiveAuthorityKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAckExecutiveAuthorityKeyResponse) Reset() {
	*x = MsgAckExecutiveAuthorityKeyResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAckExecutiveAuthorityKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAckExecutiveAuthorityKeyResponse) ProtoMessage() {}

func (x *MsgAckExecutiveAuthorityKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAckExecutiveAuthorityKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgAckExecutiveAuthorityKeyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{18}
}

// MsgCreateValidatorWithPallasKey wraps standard MsgCreateValidator with a Pallas public key.
// The handler creates the validator via the staking module, then registers the Pallas key
// in the ceremony state. Raw MsgCreateValidator is blocked by the ante handler for live txs.
type MsgCreateValidatorWithPallasKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakingMsg    []byte                 `protobuf:"bytes,1,opt,name=staking_msg,json=stakingMsg,proto3" json:"staking_msg,omitempty"` // Encoded cosmos.staking.v1beta1.MsgCreateValidator
	PallasPk      []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"`       // Compressed Pallas point (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateValidatorWithPallasKey) Reset() {
	*x = MsgCreateValidatorWithPallasKey{}
	mi := &file_svote_v1_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateValidatorWithPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateValidatorWithPallasKey) ProtoMessage() {}

func (x *MsgCreateValidatorWithPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateValidatorWithPallasKey.ProtoReflect.Descriptor instead.
func (*MsgCreateValidatorWithPallasKey) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{19}
}

func (x *MsgCreateValidatorWithPallasKey) GetStakingMsg() []byte {
	if x != nil {
		return x.StakingMsg
	}
	return nil
}

func (x *MsgCreateValidatorWithPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

type MsgCreateValidatorWithPallasKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateValidatorWithPallasKeyResponse) Reset() {
	*x = MsgCreateValidatorWithPallasKeyResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateValidatorWithPallasKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateValidatorWithPallasKeyResponse) ProtoMessage() {}

func (x *MsgCreateValidatorWithPallasKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateValidatorWithPallasKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateValidatorWithPallasKeyResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{20}
}

// MsgSubmitPartialDecryption is submitted by a validator during the TALLYING phase.
// The validator computes D_i = share_i * C1 for each (proposal, decision) accumulator
// and submits all entries in a single message. In Step 1 there is no dleq_proof;
// that field is added in Step 2.
type MsgSubmitPartialDecryption struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	VoteRoundId    []byte                    `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Creator        string                    `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`                                      // Validator operator address
	ValidatorIndex uint32                    `protobuf:"varint,3,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"` // 1-based index matching Shamir evaluation point
	Entries        []*PartialDecryptionEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgSubmitPartialDecryption) Reset() {
	*x = MsgSubmitPartialDecryption{}
	mi := &file_svote_v1_tx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitPartialDecryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitPartialDecryption) ProtoMessage() {}

func (x *MsgSubmitPartialDecryption) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitPartialDecryption.ProtoReflect.Descriptor instead.
func (*MsgSubmitPartialDecryption) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{21}
}

func (x *MsgSubmitPartialDecryption) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgSubmitPartialDecryption) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSubmitPartialDecryption) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *MsgSubmitPartialDecryption) GetEntries() []*PartialDecryptionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// PartialDecryptionEntry holds one partial decryption D_i = share_i * C1 for a
// single (proposal_id, vote_decision) accumulator.
// dleq_proof is reserved for Step 2 (DLEQ correctness proofs) and must be empty in Step 1.
type PartialDecryptionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProposalId     uint32                 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision   uint32                 `protobuf:"varint,2,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	PartialDecrypt []byte                 `protobuf:"bytes,3,opt,name=partial_decrypt,json=partialDecrypt,proto3" json:"partial_decrypt,omitempty"` // 32 bytes: compressed Pallas point D_i = share_i * C1
	DleqProof      []byte                 `protobuf:"bytes,4,opt,name=dleq_proof,json=dleqProof,proto3" json:"dleq_proof,omitempty"`                // reserved — populated in Step 2
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartialDecryptionEntry) Reset() {
	*x = PartialDecryptionEntry{}
	mi := &file_svote_v1_tx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecryptionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptionEntry) ProtoMessage() {}

func (x *PartialDecryptionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptionEntry.ProtoReflect.Descriptor instead.
func (*PartialDecryptionEntry) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{22}
}

func (x *PartialDecryptionEntry) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *PartialDecryptionEntry) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *PartialDecryptionEntry) GetPartialDecrypt() []byte {
	if x != nil {
		return x.PartialDecrypt
	}
	return nil
}

func (x *PartialDecryptionEntry) GetDleqProof() []byte {
	if x != nil {
		return x.DleqProof
	}
	return nil
}

type MsgSubmitPartialDecryptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitPartialDecryptionResponse) Reset() {
	*x = MsgSubmitPartialDecryptionResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitPartialDecryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitPartialDecryptionResponse) ProtoMessage() {}

func (x *MsgSubmitPartialDecryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitPartialDecryptionResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitPartialDecryptionResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{23}
}

// MsgUpdateVoteManagers atomically replaces the vote-manager set with new_vote_managers.
// Callable by any current vote manager. Does NOT move balances — each vote manager holds
// their own funds (the bank-module per-account balance). Validation:
// new_vote_managers must be non-empty, each entry a valid bech32 address, and no
// duplicates (addresses normalized before compare).
type MsgUpdateVoteManagers struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Creator         string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                                          // Sender address (must be in the current vote manager set)
	NewVoteManagers []string               `protobuf:"bytes,2,rep,name=new_vote_managers,json=newVoteManagers,proto3" json:"new_vote_managers,omitempty"` // Full replacement set
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgUpdateVoteManagers) Reset() {
	*x = MsgUpdateVoteManagers{}
	mi := &file_svote_v1_tx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateVoteManagers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateVoteManagers) ProtoMessage() {}

func (x *MsgUpdateVoteManagers) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateVoteManagers.ProtoReflect.Descriptor instead.
func (*MsgUpdateVoteManagers) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{24}
}

func (x *MsgUpdateVoteManagers) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgUpdateVoteManagers) GetNewVoteManagers() []string {
	if x != nil {
		return x.NewVoteManagers
	}
	return nil
}

type MsgUpdateVoteManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateVoteManagersResponse) Reset() {
	*x = MsgUpdateVoteManagersResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateVoteManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateVoteManagersResponse) ProtoMessage() {}

func (x *MsgUpdateVoteManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateVoteManagersResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateVoteManagersResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{25}
}

// MsgAuthorizedSend is the only way to transfer coins on this chain.
// Standard bank MsgSend and MsgMultiSend are disabled at the ante-handler
// level because unrestricted transfers would let anyone accumulate enough
// stake to create a validator, bypassing the controlled validator set.
//
// Authorization rules:
//   - Any vote manager can send to anyone (distributes stake to new validators).
//   - Bonded validators can send to any vote manager or to other bonded validators.
//   - All other senders are rejected.
type MsgAuthorizedSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Integer string, e.g. "1000000"
	Denom         string                 `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`   // e.g. "usvote"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAuthorizedSend) Reset() {
	*x = MsgAuthorizedSend{}
	mi := &file_svote_v1_tx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAuthorizedSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAuthorizedSend) ProtoMessage() {}

func (x *MsgAuthorizedSend) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAuthorizedSend.ProtoReflect.Descriptor instead.
func (*MsgAuthorizedSend) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{26}
}

func (x *MsgAuthorizedSend) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *MsgAuthorizedSend) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MsgAuthorizedSend) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgAuthorizedSend) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type MsgAuthorizedSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAuthorizedSendResponse) Reset() {
	*x = MsgAuthorizedSendResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAuthorizedSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAuthorizedSendResponse) ProtoMessage() {}

func (x *MsgAuthorizedSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAuthorizedSendResponse.ProtoReflect.Descriptor instead.
func (*MsgAuthorizedSendResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{27}
}

// MsgScheduleUpgrade schedules a software upgrade through x/upgrade.
// Callable by any current vote manager. The message intentionally keeps the
// wire shape primitive instead of embedding cosmos.upgrade.v1beta1.Plan so the
// vote module owns the public upgrade-control surface.
type MsgScheduleUpgrade struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Creator         string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                                         // Sender address (must be in the current vote manager set)
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                               // Upgrade plan name; must match the future binary's registered handler
	Height          int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                                          // Upgrade height; x/upgrade rejects past heights
	Info            string                 `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`                                               // Operator-readable upgrade metadata
	ReplaceExisting bool                   `protobuf:"varint,5,opt,name=replace_existing,json=replaceExisting,proto3" json:"replace_existing,omitempty"` // Required to overwrite an existing scheduled plan
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgScheduleUpgrade) Reset() {
	*x = MsgScheduleUpgrade{}
	mi := &file_svote_v1_tx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScheduleUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScheduleUpgrade) ProtoMessage() {}

func (x *MsgScheduleUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScheduleUpgrade.ProtoReflect.Descriptor instead.
func (*MsgScheduleUpgrade) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{28}
}

func (x *MsgScheduleUpgrade) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgScheduleUpgrade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgScheduleUpgrade) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MsgScheduleUpgrade) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *MsgScheduleUpgrade) GetReplaceExisting() bool {
	if x != nil {
		return x.ReplaceExisting
	}
	return false
}

type MsgScheduleUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgScheduleUpgradeResponse) Reset() {
	*x = MsgScheduleUpgradeResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScheduleUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScheduleUpgradeResponse) ProtoMessage() {}

func (x *MsgScheduleUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScheduleUpgradeResponse.ProtoReflect.Descriptor instead.
func (*MsgScheduleUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{29}
}

// MsgCancelUpgrade clears the currently scheduled x/upgrade plan.
// Callable by any current vote manager.
type MsgCancelUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"` // Sender address (must be in the current vote manager set)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCancelUpgrade) Reset() {
	*x = MsgCancelUpgrade{}
	mi := &file_svote_v1_tx_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCancelUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCancelUpgrade) ProtoMessage() {}

func (x *MsgCancelUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCancelUpgrade.ProtoReflect.Descriptor instead.
func (*MsgCancelUpgrade) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{30}
}

func (x *MsgCancelUpgrade) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type MsgCancelUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCancelUpgradeResponse) Reset() {
	*x = MsgCancelUpgradeResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCancelUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCancelUpgradeResponse) ProtoMessage() {}

func (x *MsgCancelUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCancelUpgradeResponse.ProtoReflect.Descriptor instead.
func (*MsgCancelUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{31}
}

// MsgSetEndorser creates, rotates, or clears an endorser_id -> bech32 address
// mapping. Only vote managers may execute this message. An empty address clears
// the mapping; existing endorsements remain queryable.
type MsgSetEndorser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                         // Sender address (must be a current vote manager)
	EndorserId    string                 `protobuf:"bytes,2,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"` // Stable identifier, e.g. "zodl"
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                         // Canonicalized on-chain; empty clears the mapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetEndorser) Reset() {
	*x = MsgSetEndorser{}
	mi := &file_svote_v1_tx_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetEndorser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetEndorser) ProtoMessage() {}

func (x *MsgSetEndorser) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetEndorser.ProtoReflect.Descriptor instead.
func (*MsgSetEndorser) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{32}
}

func (x *MsgSetEndorser) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSetEndorser) GetEndorserId() string {
	if x != nil {
		return x.EndorserId
	}
	return ""
}

func (x *MsgSetEndorser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MsgSetEndorserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetEndorserResponse) Reset() {
	*x = MsgSetEndorserResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetEndorserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetEndorserResponse) ProtoMessage() {}

func (x *MsgSetEndorserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetEndorserResponse.ProtoReflect.Descriptor instead.
func (*MsgSetEndorserResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{33}
}

// MsgEndorseRound records that endorser_id endorses vote_round_id. Only the
// current address mapped to endorser_id may execute this message.
type MsgEndorseRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EndorserId    string                 `protobuf:"bytes,2,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"`
	VoteRoundId   []byte                 `protobuf:"bytes,3,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndorseRound) Reset() {
	*x = MsgEndorseRound{}
	mi := &file_svote_v1_tx_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndorseRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndorseRound) ProtoMessage() {}

func (x *MsgEndorseRound) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndorseRound.ProtoReflect.Descriptor instead.
func (*MsgEndorseRound) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{34}
}

func (x *MsgEndorseRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgEndorseRound) GetEndorserId() string {
	if x != nil {
		return x.EndorserId
	}
	return ""
}

func (x *MsgEndorseRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type MsgEndorseRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndorseRoundResponse) Reset() {
	*x = MsgEndorseRoundResponse{}
	mi := &file_svote_v1_tx_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndorseRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndorseRoundResponse) ProtoMessage() {}

func (x *MsgEndorseRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_tx_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndorseRoundResponse.ProtoReflect.Descriptor instead.
func (*MsgEndorseRoundResponse) Descriptor() ([]byte, []int) {
	return file_svote_v1_tx_proto_rawDescGZIP(), []int{35}
}

var File_svote_v1_tx_proto protoreflect.FileDescriptor

const file_svote_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x11svote/v1/tx.proto\x12\bsvote.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14svote/v1/types.proto\"\xad\x03\n" +
	"\x16MsgCreateVotingSession\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x120\n" +
	"\tproposals\x18\b \x03(\v2\x12.svote.v1.ProposalR\tproposals\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12%\n" +
	"\x0ediscussion_url\x18\v \x01(\tR\rdiscussionUrl\"D\n" +
	"\x1eMsgCreateVotingSessionResponse\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"\xa8\x02\n" +
	"\x0fMsgDelegateVote\x12\x0e\n" +
	"\x02rk\x18\x01 \x01(\fR\x02rk\x12$\n" +
	"\x0espend_auth_sig\x18\x02 \x01(\fR\fspendAuthSig\x122\n" +
	"\x15signed_note_nullifier\x18\x03 \x01(\fR\x13signedNoteNullifier\x12\x17\n" +
	"\acmx_new\x18\x04 \x01(\fR\x06cmxNew\x12\x17\n" +
	"\avan_cmx\x18\x06 \x01(\fR\x06vanCmx\x12%\n" +
	"\x0egov_nullifiers\x18\a \x03(\fR\rgovNullifiers\x12\x14\n" +
	"\x05proof\x18\b \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\t \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\asighash\x18\n" +
	" \x01(\fR\asighash\"\x19\n" +
	"\x17MsgDelegateVoteResponse\"\xe6\x02\n" +
	"\vMsgCastVote\x12#\n" +
	"\rvan_nullifier\x18\x01 \x01(\fR\fvanNullifier\x125\n" +
	"\x17vote_authority_note_new\x18\x02 \x01(\fR\x14voteAuthorityNoteNew\x12'\n" +
	"\x0fvote_commitment\x18\x03 \x01(\fR\x0evoteCommitment\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\rR\n" +
	"proposalId\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\x12\"\n" +
	"\rvote_auth_sig\x18\n" +
	" \x01(\fR\vvoteAuthSig\x12\x13\n" +
	"\x05r_vpk\x18\f \x01(\fR\x04rVpk\"\x15\n" +
	"\x13MsgCastVoteResponse\"\x96\x02\n" +
	"\x0eMsgRevealShare\x12'\n" +
	"\x0fshare_nullifier\x18\x01 \x01(\fR\x0eshareNullifier\x12\x1b\n" +
	"\tenc_share\x18\x02 \x01(\fR\bencShare\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x04 \x01(\rR\fvoteDecision\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"\x18\n" +
	"\x16MsgRevealShareResponse\"~\n" +
	"\x0eMsgSubmitTally\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.svote.v1.TallyEntryR\aentries\"\x9e\x01\n" +
	"\n" +
	"TallyEntry\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x02 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x03 \x01(\x04R\n" +
	"totalValue\x12)\n" +
	"\x10decryption_proof\x18\x04 \x01(\fR\x0fdecryptionProof\"E\n" +
	"\x16MsgSubmitTallyResponse\x12+\n" +
	"\x11finalized_entries\x18\x01 \x01(\rR\x10finalizedEntries\"M\n" +
	"\x14MsgRegisterPallasKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\"\x1e\n" +
	"\x1cMsgRegisterPallasKeyResponse\"R\n" +
	"\x12MsgRotatePallasKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\"\n" +
	"\rnew_pallas_pk\x18\x02 \x01(\fR\vnewPallasPk\"\x1c\n" +
	"\x1aMsgRotatePallasKeyResponse\"\xb6\x01\n" +
	"\x10MsgContributeDKG\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\"\n" +
	"\rvote_round_id\x18\x02 \x01(\fR\vvoteRoundId\x12/\n" +
	"\x13feldman_commitments\x18\x03 \x03(\fR\x12feldmanCommitments\x123\n" +
	"\bpayloads\x18\x04 \x03(\v2\x17.svote.v1.DealerPayloadR\bpayloads\"\x1a\n" +
	"\x18MsgContributeDKGResponse\"\x80\x01\n" +
	"\x1bMsgAckExecutiveAuthorityKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12#\n" +
	"\rack_signature\x18\x02 \x01(\fR\fackSignature\x12\"\n" +
	"\rvote_round_id\x18\x03 \x01(\fR\vvoteRoundId\"%\n" +
	"#MsgAckExecutiveAuthorityKeyResponse\"_\n" +
	"\x1fMsgCreateValidatorWithPallasKey\x12\x1f\n" +
	"\vstaking_msg\x18\x01 \x01(\fR\n" +
	"stakingMsg\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\")\n" +
	"'MsgCreateValidatorWithPallasKeyResponse\"\xbf\x01\n" +
	"\x1aMsgSubmitPartialDecryption\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12'\n" +
	"\x0fvalidator_index\x18\x03 \x01(\rR\x0evalidatorIndex\x12:\n" +
	"\aentries\x18\x04 \x03(\v2 .svote.v1.PartialDecryptionEntryR\aentries\"\xa6\x01\n" +
	"\x16PartialDecryptionEntry\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x02 \x01(\rR\fvoteDecision\x12'\n" +
	"\x0fpartial_decrypt\x18\x03 \x01(\fR\x0epartialDecrypt\x12\x1d\n" +
	"\n" +
	"dleq_proof\x18\x04 \x01(\fR\tdleqProof\"$\n" +
	"\"MsgSubmitPartialDecryptionResponse\"]\n" +
	"\x15MsgUpdateVoteManagers\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12*\n" +
	"\x11new_vote_managers\x18\x02 \x03(\tR\x0fnewVoteManagers\"\x1f\n" +
	"\x1dMsgUpdateVoteManagersResponse\"\x83\x01\n" +
	"\x11MsgAuthorizedSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x04 \x01(\tR\x05denom\"\x1b\n" +
	"\x19MsgAuthorizedSendResponse\"\x99\x01\n" +
	"\x12MsgScheduleUpgrade\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x03R\x06height\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\x12)\n" +
	"\x10replace_existing\x18\x05 \x01(\bR\x0freplaceExisting\"\x1c\n" +
	"\x1aMsgScheduleUpgradeResponse\",\n" +
	"\x10MsgCancelUpgrade\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\"\x1a\n" +
	"\x18MsgCancelUpgradeResponse\"s\n" +
	"\x0eMsgSetEndorser\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1f\n" +
	"\vendorser_id\x18\x02 \x01(\tR\n" +
	"endorserId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress:\f\x82\xe7\xb0*\acreator\"\x18\n" +
	"\x16MsgSetEndorserResponse\"~\n" +
	"\x0fMsgEndorseRound\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1f\n" +
	"\vendorser_id\x18\x02 \x01(\tR\n" +
	"endorserId\x12\"\n" +
	"\rvote_round_id\x18\x03 \x01(\fR\vvoteRoundId:\f\x82\xe7\xb0*\acreator\"\x19\n" +
	"\x17MsgEndorseRoundResponse2\xee\v\n" +
	"\x03Msg\x12a\n" +
	"\x13CreateVotingSession\x12 .svote.v1.MsgCreateVotingSession\x1a(.svote.v1.MsgCreateVotingSessionResponse\x12L\n" +
	"\fDelegateVote\x12\x19.svote.v1.MsgDelegateVote\x1a!.svote.v1.MsgDelegateVoteResponse\x12@\n" +
	"\bCastVote\x12\x15.svote.v1.MsgCastVote\x1a\x1d.svote.v1.MsgCastVoteResponse\x12I\n" +
	"\vRevealShare\x12\x18.svote.v1.MsgRevealShare\x1a .svote.v1.MsgRevealShareResponse\x12I\n" +
	"\vSubmitTally\x12\x18.svote.v1.MsgSubmitTally\x1a .svote.v1.MsgSubmitTallyResponse\x12m\n" +
	"\x17SubmitPartialDecryption\x12$.svote.v1.MsgSubmitPartialDecryption\x1a,.svote.v1.MsgSubmitPartialDecryptionResponse\x12[\n" +
	"\x11RegisterPallasKey\x12\x1e.svote.v1.MsgRegisterPallasKey\x1a&.svote.v1.MsgRegisterPallasKeyResponse\x12U\n" +
	"\x0fRotatePallasKey\x12\x1c.svote.v1.MsgRotatePallasKey\x1a$.svote.v1.MsgRotatePallasKeyResponse\x12O\n" +
	"\rContributeDKG\x12\x1a.svote.v1.MsgContributeDKG\x1a\".svote.v1.MsgContributeDKGResponse\x12p\n" +
	"\x18AckExecutiveAuthorityKey\x12%.svote.v1.MsgAckExecutiveAuthorityKey\x1a-.svote.v1.MsgAckExecutiveAuthorityKeyResponse\x12|\n" +
	"\x1cCreateValidatorWithPallasKey\x12).svote.v1.MsgCreateValidatorWithPallasKey\x1a1.svote.v1.MsgCreateValidatorWithPallasKeyResponse\x12^\n" +
	"\x12UpdateVoteManagers\x12\x1f.svote.v1.MsgUpdateVoteManagers\x1a'.svote.v1.MsgUpdateVoteManagersResponse\x12R\n" +
	"\x0eAuthorizedSend\x12\x1b.svote.v1.MsgAuthorizedSend\x1a#.svote.v1.MsgAuthorizedSendResponse\x12U\n" +
	"\x0fScheduleUpgrade\x12\x1c.svote.v1.MsgScheduleUpgrade\x1a$.svote.v1.MsgScheduleUpgradeResponse\x12O\n" +
	"\rCancelUpgrade\x12\x1a.svote.v1.MsgCancelUpgrade\x1a\".svote.v1.MsgCancelUpgradeResponse\x12I\n" +
	"\vSetEndorser\x12\x18.svote.v1.MsgSetEndorser\x1a .svote.v1.MsgSetEndorserResponse\x12L\n" +
	"\fEndorseRound\x12\x19.svote.v1.MsgEndorseRound\x1a!.svote.v1.MsgEndorseRoundResponse\x1a\x05\x80\xe7\xb0*\x01B-Z+github.com/valargroup/vote-sdk/x/vote/typesb\x06proto3"

var (
	file_svote_v1_tx_proto_rawDescOnce sync.Once
	file_svote_v1_tx_proto_rawDescData []byte
)

func file_svote_v1_tx_proto_rawDescGZIP() []byte {
	file_svote_v1_tx_proto_rawDescOnce.Do(func() {
		file_svote_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svote_v1_tx_proto_rawDesc), len(file_svote_v1_tx_proto_rawDesc)))
	})
	return file_svote_v1_tx_proto_rawDescData
}

var file_svote_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_svote_v1_tx_proto_goTypes = []any{
	(*MsgCreateVotingSession)(nil),                  // 0: svote.v1.MsgCreateVotingSession
	(*MsgCreateVotingSessionResponse)(nil),          // 1: svote.v1.MsgCreateVotingSessionResponse
	(*MsgDelegateVote)(nil),                         // 2: svote.v1.MsgDelegateVote
	(*MsgDelegateVoteResponse)(nil),                 // 3: svote.v1.MsgDelegateVoteResponse
	(*MsgCastVote)(nil),                             // 4: svote.v1.MsgCastVote
	(*MsgCastVoteResponse)(nil),                     // 5: svote.v1.MsgCastVoteResponse
	(*MsgRevealShare)(nil),                          // 6: svote.v1.MsgRevealShare
	(*MsgRevealShareResponse)(nil),                  // 7: svote.v1.MsgRevealShareResponse
	(*MsgSubmitTally)(nil),                          // 8: svote.v1.MsgSubmitTally
	(*TallyEntry)(nil),                              // 9: svote.v1.TallyEntry
	(*MsgSubmitTallyResponse)(nil),                  // 10: svote.v1.MsgSubmitTallyResponse
	(*MsgRegisterPallasKey)(nil),                    // 11: svote.v1.MsgRegisterPallasKey
	(*MsgRegisterPallasKeyResponse)(nil),            // 12: svote.v1.MsgRegisterPallasKeyResponse
	(*MsgRotatePallasKey)(nil),                      // 13: svote.v1.MsgRotatePallasKey
	(*MsgRotatePallasKeyResponse)(nil),              // 14: svote.v1.MsgRotatePallasKeyResponse
	(*MsgContributeDKG)(nil),                        // 15: svote.v1.MsgContributeDKG
	(*MsgContributeDKGResponse)(nil),                // 16: svote.v1.MsgContributeDKGResponse
	(*MsgAckExecutiveAuthorityKey)(nil),             // 17: svote.v1.MsgAckExecutiveAuthorityKey
	(*MsgAckExecutiveAuthorityKeyResponse)(nil),     // 18: svote.v1.MsgAckExecutiveAuthorityKeyResponse
	(*MsgCreateValidatorWithPallasKey)(nil),         // 19: svote.v1.MsgCreateValidatorWithPallasKey
	(*MsgCreateValidatorWithPallasKeyResponse)(nil), // 20: svote.v1.MsgCreateValidatorWithPallasKeyResponse
	(*MsgSubmitPartialDecryption)(nil),              // 21: svote.v1.MsgSubmitPartialDecryption
	(*PartialDecryptionEntry)(nil),                  // 22: svote.v1.PartialDecryptionEntry
	(*MsgSubmitPartialDecryptionResponse)(nil),      // 23: svote.v1.MsgSubmitPartialDecryptionResponse
	(*MsgUpdateVoteManagers)(nil),                   // 24: svote.v1.MsgUpdateVoteManagers
	(*MsgUpdateVoteManagersResponse)(nil),           // 25: svote.v1.MsgUpdateVoteManagersResponse
	(*MsgAuthorizedSend)(nil),                       // 26: svote.v1.MsgAuthorizedSend
	(*MsgAuthorizedSendResponse)(nil),               // 27: svote.v1.MsgAuthorizedSendResponse
	(*MsgScheduleUpgrade)(nil),                      // 28: svote.v1.MsgScheduleUpgrade
	(*MsgScheduleUpgradeResponse)(nil),              // 29: svote.v1.MsgScheduleUpgradeResponse
	(*MsgCancelUpgrade)(nil),                        // 30: svote.v1.MsgCancelUpgrade
	(*MsgCancelUpgradeResponse)(nil),                // 31: svote.v1.MsgCancelUpgradeResponse
	(*MsgSetEndorser)(nil),                          // 32: svote.v1.MsgSetEndorser
	(*MsgSetEndorserResponse)(nil),                  // 33: svote.v1.MsgSetEndorserResponse
	(*MsgEndorseRound)(nil),                         // 34: svote.v1.MsgEndorseRound
	(*MsgEndorseRoundResponse)(nil),                 // 35: svote.v1.MsgEndorseRoundResponse
	(*Proposal)(nil),                                // 36: svote.v1.Proposal
	(*DealerPayload)(nil),                           // 37: svote.v1.DealerPayload
}
var file_svote_v1_tx_proto_depIdxs = []int32{
	36, // 0: svote.v1.MsgCreateVotingSession.proposals:type_name -> svote.v1.Proposal
	9,  // 1: svote.v1.MsgSubmitTally.entries:type_name -> svote.v1.TallyEntry
	37, // 2: svote.v1.MsgContributeDKG.payloads:type_name -> svote.v1.DealerPayload
	22, // 3: svote.v1.MsgSubmitPartialDecryption.entries:type_name -> svote.v1.PartialDecryptionEntry
	0,  // 4: svote.v1.Msg.CreateVotingSession:input_type -> svote.v1.MsgCreateVotingSession
	2,  // 5: svote.v1.Msg.DelegateVote:input_type -> svote.v1.MsgDelegateVote
	4,  // 6: svote.v1.Msg.CastVote:input_type -> svote.v1.MsgCastVote
	6,  // 7: svote.v1.Msg.RevealShare:input_type -> svote.v1.MsgRevealShare
	8,  // 8: svote.v1.Msg.SubmitTally:input_type -> svote.v1.MsgSubmitTally
	21, // 9: svote.v1.Msg.SubmitPartialDecryption:input_type -> svote.v1.MsgSubmitPartialDecryption
	11, // 10: svote.v1.Msg.RegisterPallasKey:input_type -> svote.v1.MsgRegisterPallasKey
	13, // 11: svote.v1.Msg.RotatePallasKey:input_type -> svote.v1.MsgRotatePallasKey
	15, // 12: svote.v1.Msg.ContributeDKG:input_type -> svote.v1.MsgContributeDKG
	17, // 13: svote.v1.Msg.AckExecutiveAuthorityKey:input_type -> svote.v1.MsgAckExecutiveAuthorityKey
	19, // 14: svote.v1.Msg.CreateValidatorWithPallasKey:input_type -> svote.v1.MsgCreateValidatorWithPallasKey
	24, // 15: svote.v1.Msg.UpdateVoteManagers:input_type -> svote.v1.MsgUpdateVoteManagers
	26, // 16: svote.v1.Msg.AuthorizedSend:input_type -> svote.v1.MsgAuthorizedSend
	28, // 17: svote.v1.Msg.ScheduleUpgrade:input_type -> svote.v1.MsgScheduleUpgrade
	30, // 18: svote.v1.Msg.CancelUpgrade:input_type -> svote.v1.MsgCancelUpgrade
	32, // 19: svote.v1.Msg.SetEndorser:input_type -> svote.v1.MsgSetEndorser
	34, // 20: svote.v1.Msg.EndorseRound:input_type -> svote.v1.MsgEndorseRound
	1,  // 21: svote.v1.Msg.CreateVotingSession:output_type -> svote.v1.MsgCreateVotingSessionResponse
	3,  // 22: svote.v1.Msg.DelegateVote:output_type -> svote.v1.MsgDelegateVoteResponse
	5,  // 23: svote.v1.Msg.CastVote:output_type -> svote.v1.MsgCastVoteResponse
	7,  // 24: svote.v1.Msg.RevealShare:output_type -> svote.v1.MsgRevealShareResponse
	10, // 25: svote.v1.Msg.SubmitTally:output_type -> svote.v1.MsgSubmitTallyResponse
	23, // 26: svote.v1.Msg.SubmitPartialDecryption:output_type -> svote.v1.MsgSubmitPartialDecryptionResponse
	12, // 27: svote.v1.Msg.RegisterPallasKey:output_type -> svote.v1.MsgRegisterPallasKeyResponse
	14, // 28: svote.v1.Msg.RotatePallasKey:output_type -> svote.v1.MsgRotatePallasKeyResponse
	16, // 29: svote.v1.Msg.ContributeDKG:output_type -> svote.v1.MsgContributeDKGResponse
	18, // 30: svote.v1.Msg.AckExecutiveAuthorityKey:output_type -> svote.v1.MsgAckExecutiveAuthorityKeyResponse
	20, // 31: svote.v1.Msg.CreateValidatorWithPallasKey:output_type -> svote.v1.MsgCreateValidatorWithPallasKeyResponse
	25, // 32: svote.v1.Msg.UpdateVoteManagers:output_type -> svote.v1.MsgUpdateVoteManagersResponse
	27, // 33: svote.v1.Msg.AuthorizedSend:output_type -> svote.v1.MsgAuthorizedSendResponse
	29, // 34: svote.v1.Msg.ScheduleUpgrade:output_type -> svote.v1.MsgScheduleUpgradeResponse
	31, // 35: svote.v1.Msg.CancelUpgrade:output_type -> svote.v1.MsgCancelUpgradeResponse
	33, // 36: svote.v1.Msg.SetEndorser:output_type -> svote.v1.MsgSetEndorserResponse
	35, // 37: svote.v1.Msg.EndorseRound:output_type -> svote.v1.MsgEndorseRoundResponse
	21, // [21:38] is the sub-list for method output_type
	4,  // [4:21] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_svote_v1_tx_proto_init() }
func file_svote_v1_tx_proto_init() {
	if File_svote_v1_tx_proto != nil {
		return
	}
	file_svote_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svote_v1_tx_proto_rawDesc), len(file_svote_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svote_v1_tx_proto_goTypes,
		DependencyIndexes: file_svote_v1_tx_proto_depIdxs,
		MessageInfos:      file_svote_v1_tx_proto_msgTypes,
	}.Build()
	File_svote_v1_tx_proto = out.File
	file_svote_v1_tx_proto_goTypes = nil
	file_svote_v1_tx_proto_depIdxs = nil
}
