// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: svote/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus represents the lifecycle state of a voting session.
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED     SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE          SessionStatus = 1
	SessionStatus_SESSION_STATUS_TALLYING        SessionStatus = 2
	SessionStatus_SESSION_STATUS_FINALIZED       SessionStatus = 3
	SessionStatus_SESSION_STATUS_PENDING         SessionStatus = 4 // Ceremony in progress, not yet active
	SessionStatus_SESSION_STATUS_CEREMONY_FAILED SessionStatus = 5 // Ceremony timed out before reaching ACTIVE
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_TALLYING",
		3: "SESSION_STATUS_FINALIZED",
		4: "SESSION_STATUS_PENDING",
		5: "SESSION_STATUS_CEREMONY_FAILED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":     0,
		"SESSION_STATUS_ACTIVE":          1,
		"SESSION_STATUS_TALLYING":        2,
		"SESSION_STATUS_FINALIZED":       3,
		"SESSION_STATUS_PENDING":         4,
		"SESSION_STATUS_CEREMONY_FAILED": 5,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_svote_v1_types_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_svote_v1_types_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{0}
}

// CoordinatorActionStatus is the lifecycle of a proposed coordinator action.
type CoordinatorActionStatus int32

const (
	CoordinatorActionStatus_COORDINATOR_ACTION_STATUS_UNSPECIFIED CoordinatorActionStatus = 0
	CoordinatorActionStatus_COORDINATOR_ACTION_STATUS_PENDING     CoordinatorActionStatus = 1
	CoordinatorActionStatus_COORDINATOR_ACTION_STATUS_EXECUTED    CoordinatorActionStatus = 2
	CoordinatorActionStatus_COORDINATOR_ACTION_STATUS_EXPIRED     CoordinatorActionStatus = 3
)

// Enum value maps for CoordinatorActionStatus.
var (
	CoordinatorActionStatus_name = map[int32]string{
		0: "COORDINATOR_ACTION_STATUS_UNSPECIFIED",
		1: "COORDINATOR_ACTION_STATUS_PENDING",
		2: "COORDINATOR_ACTION_STATUS_EXECUTED",
		3: "COORDINATOR_ACTION_STATUS_EXPIRED",
	}
	CoordinatorActionStatus_value = map[string]int32{
		"COORDINATOR_ACTION_STATUS_UNSPECIFIED": 0,
		"COORDINATOR_ACTION_STATUS_PENDING":     1,
		"COORDINATOR_ACTION_STATUS_EXECUTED":    2,
		"COORDINATOR_ACTION_STATUS_EXPIRED":     3,
	}
)

func (x CoordinatorActionStatus) Enum() *CoordinatorActionStatus {
	p := new(CoordinatorActionStatus)
	*p = x
	return p
}

func (x CoordinatorActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinatorActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_svote_v1_types_proto_enumTypes[1].Descriptor()
}

func (CoordinatorActionStatus) Type() protoreflect.EnumType {
	return &file_svote_v1_types_proto_enumTypes[1]
}

func (x CoordinatorActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinatorActionStatus.Descriptor instead.
func (CoordinatorActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{1}
}

// CeremonyStatus represents the lifecycle state of the EA key ceremony.
type CeremonyStatus int32

const (
	CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED CeremonyStatus = 0
	CeremonyStatus_CEREMONY_STATUS_REGISTERING CeremonyStatus = 1 // Accepting validator pk_i registrations (no timeout)
	CeremonyStatus_CEREMONY_STATUS_DEALT       CeremonyStatus = 2 // DealerTx landed, awaiting acks
	CeremonyStatus_CEREMONY_STATUS_CONFIRMED   CeremonyStatus = 3 // All acked (fast path) or required quorum acked at timeout, ea_pk ready
)

// Enum value maps for CeremonyStatus.
var (
	CeremonyStatus_name = map[int32]string{
		0: "CEREMONY_STATUS_UNSPECIFIED",
		1: "CEREMONY_STATUS_REGISTERING",
		2: "CEREMONY_STATUS_DEALT",
		3: "CEREMONY_STATUS_CONFIRMED",
	}
	CeremonyStatus_value = map[string]int32{
		"CEREMONY_STATUS_UNSPECIFIED": 0,
		"CEREMONY_STATUS_REGISTERING": 1,
		"CEREMONY_STATUS_DEALT":       2,
		"CEREMONY_STATUS_CONFIRMED":   3,
	}
)

func (x CeremonyStatus) Enum() *CeremonyStatus {
	p := new(CeremonyStatus)
	*p = x
	return p
}

func (x CeremonyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CeremonyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_svote_v1_types_proto_enumTypes[2].Descriptor()
}

func (CeremonyStatus) Type() protoreflect.EnumType {
	return &file_svote_v1_types_proto_enumTypes[2]
}

func (x CeremonyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CeremonyStatus.Descriptor instead.
func (CeremonyStatus) EnumDescriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{2}
}

// VoteOption represents a named choice within a proposal.
type VoteOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`            // 0-indexed
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`             // e.g. "Support", "Oppose"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Optional explanatory text shown under the option label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOption) Reset() {
	*x = VoteOption{}
	mi := &file_svote_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOption) ProtoMessage() {}

func (x *VoteOption) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOption.ProtoReflect.Descriptor instead.
func (*VoteOption) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *VoteOption) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VoteOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *VoteOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Proposal represents a single ballot option within a voting session.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Options       []*VoteOption          `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`                      // 2-8 named choices
	ZipNumber     string                 `protobuf:"bytes,5,opt,name=zip_number,json=zipNumber,proto3" json:"zip_number,omitempty"` // e.g. "ZIP-227"
	ForumUrl      string                 `protobuf:"bytes,6,opt,name=forum_url,json=forumUrl,proto3" json:"forum_url,omitempty"`    // Per-proposal forum discussion link
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_svote_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proposal) GetOptions() []*VoteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Proposal) GetZipNumber() string {
	if x != nil {
		return x.ZipNumber
	}
	return ""
}

func (x *Proposal) GetForumUrl() string {
	if x != nil {
		return x.ForumUrl
	}
	return ""
}

// VoteRound represents a voting session created by MsgCreateVotingSession.
type VoteRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId       []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	Creator           string                 `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Status            SessionStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=svote.v1.SessionStatus" json:"status,omitempty"`
	EaPk              []byte                 `protobuf:"bytes,10,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"` // Election authority public key (Pallas, 32 bytes)
	Proposals         []*Proposal            `protobuf:"bytes,11,rep,name=proposals,proto3" json:"proposals,omitempty"`
	Description       string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`                                   // Human-readable round description
	CreatedAtHeight   uint64                 `protobuf:"varint,13,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"` // Block height at which this round was registered on-chain
	Title             string                 `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`                                               // Short human-readable round title
	// Per-round ceremony fields (populated when status = PENDING).
	CeremonyStatus       CeremonyStatus        `protobuf:"varint,15,opt,name=ceremony_status,json=ceremonyStatus,proto3,enum=svote.v1.CeremonyStatus" json:"ceremony_status,omitempty"`
	CeremonyValidators   []*ValidatorPallasKey `protobuf:"bytes,16,rep,name=ceremony_validators,json=ceremonyValidators,proto3" json:"ceremony_validators,omitempty"`
	CeremonyAcks         []*AckEntry           `protobuf:"bytes,18,rep,name=ceremony_acks,json=ceremonyAcks,proto3" json:"ceremony_acks,omitempty"`
	CeremonyPhaseStart   uint64                `protobuf:"varint,20,opt,name=ceremony_phase_start,json=ceremonyPhaseStart,proto3" json:"ceremony_phase_start,omitempty"`
	CeremonyPhaseTimeout uint64                `protobuf:"varint,21,opt,name=ceremony_phase_timeout,json=ceremonyPhaseTimeout,proto3" json:"ceremony_phase_timeout,omitempty"`
	CeremonyLog          []string              `protobuf:"bytes,22,rep,name=ceremony_log,json=ceremonyLog,proto3" json:"ceremony_log,omitempty"` // Timestamped human-readable ceremony log entries
	// Threshold decryption fields (populated by finalizeDKG).
	// threshold is the minimum number of partial decryptions required to reconstruct the tally.
	// feldman_commitments holds C_j = a_j*G for j=0..t-1 (Feldman polynomial commitments).
	// Validators derive VK_i = EvalCommitmentPolynomial(commitments, i) for share verification.
	Threshold          uint32   `protobuf:"varint,23,opt,name=threshold,proto3" json:"threshold,omitempty"`                                            // Minimum shares for reconstruction (always >= 2)
	FeldmanCommitments [][]byte `protobuf:"bytes,24,rep,name=feldman_commitments,json=feldmanCommitments,proto3" json:"feldman_commitments,omitempty"` // C_j = a_j*G, t compressed Pallas points (32 bytes each)
	// Tally phase timeout fields (populated when status transitions to TALLYING).
	TallyPhaseStart   uint64 `protobuf:"varint,25,opt,name=tally_phase_start,json=tallyPhaseStart,proto3" json:"tally_phase_start,omitempty"`       // Unix seconds when TALLYING started
	TallyPhaseTimeout uint64 `protobuf:"varint,26,opt,name=tally_phase_timeout,json=tallyPhaseTimeout,proto3" json:"tally_phase_timeout,omitempty"` // Timeout duration in seconds (default: 6 hours)
	TallyTimedOut     bool   `protobuf:"varint,27,opt,name=tally_timed_out,json=tallyTimedOut,proto3" json:"tally_timed_out,omitempty"`             // True if round was finalized via timeout (no decrypted results)
	// DKG contributions (populated during Joint-Feldman DKG; replaces single-dealer fields once wired).
	DkgContributions []*DKGContribution `protobuf:"bytes,28,rep,name=dkg_contributions,json=dkgContributions,proto3" json:"dkg_contributions,omitempty"`
	DiscussionUrl    string             `protobuf:"bytes,29,opt,name=discussion_url,json=discussionUrl,proto3" json:"discussion_url,omitempty"`    // Overall forum discussion link for the vote round
	CreatedAtTime    uint64             `protobuf:"varint,30,opt,name=created_at_time,json=createdAtTime,proto3" json:"created_at_time,omitempty"` // Unix seconds when this round was registered on-chain
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoteRound) Reset() {
	*x = VoteRound{}
	mi := &file_svote_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRound) ProtoMessage() {}

func (x *VoteRound) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRound.ProtoReflect.Descriptor instead.
func (*VoteRound) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *VoteRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *VoteRound) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *VoteRound) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *VoteRound) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *VoteRound) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *VoteRound) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *VoteRound) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *VoteRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *VoteRound) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *VoteRound) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *VoteRound) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *VoteRound) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VoteRound) GetCreatedAtHeight() uint64 {
	if x != nil {
		return x.CreatedAtHeight
	}
	return 0
}

func (x *VoteRound) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VoteRound) GetCeremonyStatus() CeremonyStatus {
	if x != nil {
		return x.CeremonyStatus
	}
	return CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED
}

func (x *VoteRound) GetCeremonyValidators() []*ValidatorPallasKey {
	if x != nil {
		return x.CeremonyValidators
	}
	return nil
}

func (x *VoteRound) GetCeremonyAcks() []*AckEntry {
	if x != nil {
		return x.CeremonyAcks
	}
	return nil
}

func (x *VoteRound) GetCeremonyPhaseStart() uint64 {
	if x != nil {
		return x.CeremonyPhaseStart
	}
	return 0
}

func (x *VoteRound) GetCeremonyPhaseTimeout() uint64 {
	if x != nil {
		return x.CeremonyPhaseTimeout
	}
	return 0
}

func (x *VoteRound) GetCeremonyLog() []string {
	if x != nil {
		return x.CeremonyLog
	}
	return nil
}

func (x *VoteRound) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *VoteRound) GetFeldmanCommitments() [][]byte {
	if x != nil {
		return x.FeldmanCommitments
	}
	return nil
}

func (x *VoteRound) GetTallyPhaseStart() uint64 {
	if x != nil {
		return x.TallyPhaseStart
	}
	return 0
}

func (x *VoteRound) GetTallyPhaseTimeout() uint64 {
	if x != nil {
		return x.TallyPhaseTimeout
	}
	return 0
}

func (x *VoteRound) GetTallyTimedOut() bool {
	if x != nil {
		return x.TallyTimedOut
	}
	return false
}

func (x *VoteRound) GetDkgContributions() []*DKGContribution {
	if x != nil {
		return x.DkgContributions
	}
	return nil
}

func (x *VoteRound) GetDiscussionUrl() string {
	if x != nil {
		return x.DiscussionUrl
	}
	return ""
}

func (x *VoteRound) GetCreatedAtTime() uint64 {
	if x != nil {
		return x.CreatedAtTime
	}
	return 0
}

// VoteManagerSet stores the vote coordinator policy.
type VoteManagerSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Threshold     uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"` // Defaults to 1 when omitted; must be <= len(addresses)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteManagerSet) Reset() {
	*x = VoteManagerSet{}
	mi := &file_svote_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteManagerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteManagerSet) ProtoMessage() {}

func (x *VoteManagerSet) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteManagerSet.ProtoReflect.Descriptor instead.
func (*VoteManagerSet) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *VoteManagerSet) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *VoteManagerSet) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// CoordinatorAction stores one pending or executed threshold-gated action.
type CoordinatorAction struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ActionId      uint64                  `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Payload       *anypb.Any              `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Proposer      string                  `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Approvals     []string                `protobuf:"bytes,4,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Status        CoordinatorActionStatus `protobuf:"varint,5,opt,name=status,proto3,enum=svote.v1.CoordinatorActionStatus" json:"status,omitempty"`
	CreatedAt     uint64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     uint64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ExecutedAt    uint64                  `protobuf:"varint,8,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorAction) Reset() {
	*x = CoordinatorAction{}
	mi := &file_svote_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorAction) ProtoMessage() {}

func (x *CoordinatorAction) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorAction.ProtoReflect.Descriptor instead.
func (*CoordinatorAction) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorAction) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *CoordinatorAction) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorAction) GetProposer() string {
	if x != nil {
		return x.Proposer
	}
	return ""
}

func (x *CoordinatorAction) GetApprovals() []string {
	if x != nil {
		return x.Approvals
	}
	return nil
}

func (x *CoordinatorAction) GetStatus() CoordinatorActionStatus {
	if x != nil {
		return x.Status
	}
	return CoordinatorActionStatus_COORDINATOR_ACTION_STATUS_UNSPECIFIED
}

func (x *CoordinatorAction) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CoordinatorAction) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CoordinatorAction) GetExecutedAt() uint64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

// CommitmentTreeState holds the current state of the append-only commitment tree.
type CommitmentTreeState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextIndex       uint64                 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`                       // Next leaf index to write
	Root            []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                                                   // Current Merkle root (empty until EndBlocker computes it)
	Height          uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                                              // Block height at which this root was last computed
	NextIndexAtRoot uint64                 `protobuf:"varint,4,opt,name=next_index_at_root,json=nextIndexAtRoot,proto3" json:"next_index_at_root,omitempty"` // NextIndex at the time the root was last stored (used to compute per-block leaf ranges)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitmentTreeState) Reset() {
	*x = CommitmentTreeState{}
	mi := &file_svote_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentTreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentTreeState) ProtoMessage() {}

func (x *CommitmentTreeState) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentTreeState.ProtoReflect.Descriptor instead.
func (*CommitmentTreeState) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *CommitmentTreeState) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *CommitmentTreeState) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CommitmentTreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommitmentTreeState) GetNextIndexAtRoot() uint64 {
	if x != nil {
		return x.NextIndexAtRoot
	}
	return 0
}

// GenesisState defines the vote module's genesis state.
type GenesisState struct {
	state                   protoimpl.MessageState      `protogen:"open.v1"`
	Rounds                  []*VoteRound                `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Nullifiers              []*NullifierEntry           `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	VoteManagerAddresses    []string                    `protobuf:"bytes,5,rep,name=vote_manager_addresses,json=voteManagerAddresses,proto3" json:"vote_manager_addresses,omitempty"`
	TallyResults            []*TallyResult              `protobuf:"bytes,6,rep,name=tally_results,json=tallyResults,proto3" json:"tally_results,omitempty"`
	PallasKeys              []*ValidatorPallasKey       `protobuf:"bytes,7,rep,name=pallas_keys,json=pallasKeys,proto3" json:"pallas_keys,omitempty"`
	TallyAccumulators       []*GenesisTallyAccumulator  `protobuf:"bytes,8,rep,name=tally_accumulators,json=tallyAccumulators,proto3" json:"tally_accumulators,omitempty"`
	ShareCounts             []*GenesisShareCount        `protobuf:"bytes,9,rep,name=share_counts,json=shareCounts,proto3" json:"share_counts,omitempty"`
	MinCeremonyValidators   uint32                      `protobuf:"varint,11,opt,name=min_ceremony_validators,json=minCeremonyValidators,proto3" json:"min_ceremony_validators,omitempty"`
	RoundTrees              []*GenesisRoundTree         `protobuf:"bytes,12,rep,name=round_trees,json=roundTrees,proto3" json:"round_trees,omitempty"`
	PartialDecryptions      []*GenesisPartialDecryption `protobuf:"bytes,13,rep,name=partial_decryptions,json=partialDecryptions,proto3" json:"partial_decryptions,omitempty"`
	Endorsers               []*Endorser                 `protobuf:"bytes,14,rep,name=endorsers,proto3" json:"endorsers,omitempty"`
	EndorsedRounds          []*EndorsedRound            `protobuf:"bytes,15,rep,name=endorsed_rounds,json=endorsedRounds,proto3" json:"endorsed_rounds,omitempty"`
	VoteManagerThreshold    uint32                      `protobuf:"varint,16,opt,name=vote_manager_threshold,json=voteManagerThreshold,proto3" json:"vote_manager_threshold,omitempty"`
	CoordinatorActions      []*CoordinatorAction        `protobuf:"bytes,17,rep,name=coordinator_actions,json=coordinatorActions,proto3" json:"coordinator_actions,omitempty"`
	NextCoordinatorActionId uint64                      `protobuf:"varint,18,opt,name=next_coordinator_action_id,json=nextCoordinatorActionId,proto3" json:"next_coordinator_action_id,omitempty"`
	UsedDelegationRks       [][]byte                    `protobuf:"bytes,19,rep,name=used_delegation_rks,json=usedDelegationRks,proto3" json:"used_delegation_rks,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_svote_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *GenesisState) GetRounds() []*VoteRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GenesisState) GetNullifiers() []*NullifierEntry {
	if x != nil {
		return x.Nullifiers
	}
	return nil
}

func (x *GenesisState) GetVoteManagerAddresses() []string {
	if x != nil {
		return x.VoteManagerAddresses
	}
	return nil
}

func (x *GenesisState) GetTallyResults() []*TallyResult {
	if x != nil {
		return x.TallyResults
	}
	return nil
}

func (x *GenesisState) GetPallasKeys() []*ValidatorPallasKey {
	if x != nil {
		return x.PallasKeys
	}
	return nil
}

func (x *GenesisState) GetTallyAccumulators() []*GenesisTallyAccumulator {
	if x != nil {
		return x.TallyAccumulators
	}
	return nil
}

func (x *GenesisState) GetShareCounts() []*GenesisShareCount {
	if x != nil {
		return x.ShareCounts
	}
	return nil
}

func (x *GenesisState) GetMinCeremonyValidators() uint32 {
	if x != nil {
		return x.MinCeremonyValidators
	}
	return 0
}

func (x *GenesisState) GetRoundTrees() []*GenesisRoundTree {
	if x != nil {
		return x.RoundTrees
	}
	return nil
}

func (x *GenesisState) GetPartialDecryptions() []*GenesisPartialDecryption {
	if x != nil {
		return x.PartialDecryptions
	}
	return nil
}

func (x *GenesisState) GetEndorsers() []*Endorser {
	if x != nil {
		return x.Endorsers
	}
	return nil
}

func (x *GenesisState) GetEndorsedRounds() []*EndorsedRound {
	if x != nil {
		return x.EndorsedRounds
	}
	return nil
}

func (x *GenesisState) GetVoteManagerThreshold() uint32 {
	if x != nil {
		return x.VoteManagerThreshold
	}
	return 0
}

func (x *GenesisState) GetCoordinatorActions() []*CoordinatorAction {
	if x != nil {
		return x.CoordinatorActions
	}
	return nil
}

func (x *GenesisState) GetNextCoordinatorActionId() uint64 {
	if x != nil {
		return x.NextCoordinatorActionId
	}
	return 0
}

func (x *GenesisState) GetUsedDelegationRks() [][]byte {
	if x != nil {
		return x.UsedDelegationRks
	}
	return nil
}

// Endorser records a stable identifier's currently authorized bech32 address.
type Endorser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndorserId    string                 `protobuf:"bytes,1,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endorser) Reset() {
	*x = Endorser{}
	mi := &file_svote_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endorser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorser) ProtoMessage() {}

func (x *Endorser) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorser.ProtoReflect.Descriptor instead.
func (*Endorser) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Endorser) GetEndorserId() string {
	if x != nil {
		return x.EndorserId
	}
	return ""
}

func (x *Endorser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// EndorsedRound records one append-only round endorsement by endorser_id.
type EndorsedRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndorserId    string                 `protobuf:"bytes,1,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"`
	VoteRoundId   []byte                 `protobuf:"bytes,2,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsedRound) Reset() {
	*x = EndorsedRound{}
	mi := &file_svote_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsedRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsedRound) ProtoMessage() {}

func (x *EndorsedRound) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsedRound.ProtoReflect.Descriptor instead.
func (*EndorsedRound) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *EndorsedRound) GetEndorserId() string {
	if x != nil {
		return x.EndorserId
	}
	return ""
}

func (x *EndorsedRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

// GenesisRoundTree holds per-round commitment tree state for genesis export/import.
type GenesisRoundTree struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	VoteRoundId      []byte                   `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	TreeState        *CommitmentTreeState     `protobuf:"bytes,2,opt,name=tree_state,json=treeState,proto3" json:"tree_state,omitempty"`
	CommitmentLeaves []*CommitmentLeaf        `protobuf:"bytes,3,rep,name=commitment_leaves,json=commitmentLeaves,proto3" json:"commitment_leaves,omitempty"`
	CommitmentRoots  []*GenesisCommitmentRoot `protobuf:"bytes,4,rep,name=commitment_roots,json=commitmentRoots,proto3" json:"commitment_roots,omitempty"`
	BlockLeafIndices []*GenesisBlockLeafIndex `protobuf:"bytes,5,rep,name=block_leaf_indices,json=blockLeafIndices,proto3" json:"block_leaf_indices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisRoundTree) Reset() {
	*x = GenesisRoundTree{}
	mi := &file_svote_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisRoundTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisRoundTree) ProtoMessage() {}

func (x *GenesisRoundTree) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisRoundTree.ProtoReflect.Descriptor instead.
func (*GenesisRoundTree) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *GenesisRoundTree) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *GenesisRoundTree) GetTreeState() *CommitmentTreeState {
	if x != nil {
		return x.TreeState
	}
	return nil
}

func (x *GenesisRoundTree) GetCommitmentLeaves() []*CommitmentLeaf {
	if x != nil {
		return x.CommitmentLeaves
	}
	return nil
}

func (x *GenesisRoundTree) GetCommitmentRoots() []*GenesisCommitmentRoot {
	if x != nil {
		return x.CommitmentRoots
	}
	return nil
}

func (x *GenesisRoundTree) GetBlockLeafIndices() []*GenesisBlockLeafIndex {
	if x != nil {
		return x.BlockLeafIndices
	}
	return nil
}

// GenesisCommitmentRoot is a commitment tree root stored at a specific block height.
type GenesisCommitmentRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisCommitmentRoot) Reset() {
	*x = GenesisCommitmentRoot{}
	mi := &file_svote_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisCommitmentRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisCommitmentRoot) ProtoMessage() {}

func (x *GenesisCommitmentRoot) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisCommitmentRoot.ProtoReflect.Descriptor instead.
func (*GenesisCommitmentRoot) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *GenesisCommitmentRoot) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GenesisCommitmentRoot) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// GenesisTallyAccumulator is an in-progress ElGamal tally ciphertext for a (round, proposal, decision) tuple.
type GenesisTallyAccumulator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       []byte                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision  uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // 64-byte ElGamal ciphertext
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisTallyAccumulator) Reset() {
	*x = GenesisTallyAccumulator{}
	mi := &file_svote_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisTallyAccumulator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisTallyAccumulator) ProtoMessage() {}

func (x *GenesisTallyAccumulator) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisTallyAccumulator.ProtoReflect.Descriptor instead.
func (*GenesisTallyAccumulator) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *GenesisTallyAccumulator) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

func (x *GenesisTallyAccumulator) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *GenesisTallyAccumulator) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *GenesisTallyAccumulator) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// GenesisShareCount is a share reveal count for a (round, proposal, decision) tuple.
type GenesisShareCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       []byte                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision  uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisShareCount) Reset() {
	*x = GenesisShareCount{}
	mi := &file_svote_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisShareCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisShareCount) ProtoMessage() {}

func (x *GenesisShareCount) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisShareCount.ProtoReflect.Descriptor instead.
func (*GenesisShareCount) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *GenesisShareCount) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

func (x *GenesisShareCount) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *GenesisShareCount) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *GenesisShareCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GenesisPartialDecryption stores one validator's partial decryption D_i for
// a single (round, proposal, decision) accumulator. Exported during TALLYING
// so validators do not need to re-submit after a chain migration.
type GenesisPartialDecryption struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoundId        []byte                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ValidatorIndex uint32                 `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	ProposalId     uint32                 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision   uint32                 `protobuf:"varint,4,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	PartialDecrypt []byte                 `protobuf:"bytes,5,opt,name=partial_decrypt,json=partialDecrypt,proto3" json:"partial_decrypt,omitempty"` // 32-byte compressed Pallas point D_i
	DleqProof      []byte                 `protobuf:"bytes,6,opt,name=dleq_proof,json=dleqProof,proto3" json:"dleq_proof,omitempty"`                // reserved for DLEQ proofs (Step 2)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenesisPartialDecryption) Reset() {
	*x = GenesisPartialDecryption{}
	mi := &file_svote_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisPartialDecryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisPartialDecryption) ProtoMessage() {}

func (x *GenesisPartialDecryption) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisPartialDecryption.ProtoReflect.Descriptor instead.
func (*GenesisPartialDecryption) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *GenesisPartialDecryption) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

func (x *GenesisPartialDecryption) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *GenesisPartialDecryption) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *GenesisPartialDecryption) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *GenesisPartialDecryption) GetPartialDecrypt() []byte {
	if x != nil {
		return x.PartialDecrypt
	}
	return nil
}

func (x *GenesisPartialDecryption) GetDleqProof() []byte {
	if x != nil {
		return x.DleqProof
	}
	return nil
}

// GenesisBlockLeafIndex records the range of commitment leaves appended during
// a specific block height. Client convenience for the CommitmentLeaves query.
type GenesisBlockLeafIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	StartIndex    uint64                 `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisBlockLeafIndex) Reset() {
	*x = GenesisBlockLeafIndex{}
	mi := &file_svote_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisBlockLeafIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisBlockLeafIndex) ProtoMessage() {}

func (x *GenesisBlockLeafIndex) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisBlockLeafIndex.ProtoReflect.Descriptor instead.
func (*GenesisBlockLeafIndex) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *GenesisBlockLeafIndex) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GenesisBlockLeafIndex) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *GenesisBlockLeafIndex) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// CommitmentLeaf is an entry in the append-only commitment tree.
type CommitmentLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentLeaf) Reset() {
	*x = CommitmentLeaf{}
	mi := &file_svote_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentLeaf) ProtoMessage() {}

func (x *CommitmentLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentLeaf.ProtoReflect.Descriptor instead.
func (*CommitmentLeaf) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *CommitmentLeaf) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitmentLeaf) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// NullifierEntry is a recorded nullifier, scoped by type and round.
type NullifierEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullifier     []byte                 `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	NullifierType uint32                 `protobuf:"varint,2,opt,name=nullifier_type,json=nullifierType,proto3" json:"nullifier_type,omitempty"` // 0=gov, 1=vote-authority-note, 2=share (maps to NullifierType)
	RoundId       []byte                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`                    // voting round this nullifier belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullifierEntry) Reset() {
	*x = NullifierEntry{}
	mi := &file_svote_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullifierEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullifierEntry) ProtoMessage() {}

func (x *NullifierEntry) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullifierEntry.ProtoReflect.Descriptor instead.
func (*NullifierEntry) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *NullifierEntry) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *NullifierEntry) GetNullifierType() uint32 {
	if x != nil {
		return x.NullifierType
	}
	return 0
}

func (x *NullifierEntry) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

// TallyResult stores a finalized vote total for one (round, proposal, decision) tuple.
// Written by MsgSubmitTally, read by the TallyResults query.
type TallyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision  uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue    uint64                 `protobuf:"varint,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"` // Decrypted aggregate (zatoshi)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TallyResult) Reset() {
	*x = TallyResult{}
	mi := &file_svote_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyResult) ProtoMessage() {}

func (x *TallyResult) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyResult.ProtoReflect.Descriptor instead.
func (*TallyResult) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *TallyResult) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *TallyResult) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyResult) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyResult) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// BlockCommitments holds the commitment leaves appended during a single block.
// Used by the CommitmentLeaves query to serve tree data to remote clients
// implementing the TreeSyncApi trait.
type BlockCommitments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`                           // Block height
	StartIndex    uint64                 `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"` // Index of the first leaf in this block
	Leaves        [][]byte               `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`                            // Commitment leaves (each 32 bytes, Pallas Fp LE)
	Root          []byte                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`                                // 32-byte tree root after this block's leaves
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommitments) Reset() {
	*x = BlockCommitments{}
	mi := &file_svote_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommitments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommitments) ProtoMessage() {}

func (x *BlockCommitments) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommitments.ProtoReflect.Descriptor instead.
func (*BlockCommitments) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *BlockCommitments) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockCommitments) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *BlockCommitments) GetLeaves() [][]byte {
	if x != nil {
		return x.Leaves
	}
	return nil
}

func (x *BlockCommitments) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// ProposalSummary is a denormalized view of a proposal for the VoteSummary query.
type ProposalSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Options       []*OptionSummary       `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalSummary) Reset() {
	*x = ProposalSummary{}
	mi := &file_svote_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalSummary) ProtoMessage() {}

func (x *ProposalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalSummary.ProtoReflect.Descriptor instead.
func (*ProposalSummary) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *ProposalSummary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProposalSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProposalSummary) GetOptions() []*OptionSummary {
	if x != nil {
		return x.Options
	}
	return nil
}

// OptionSummary is a denormalized view of a vote option for the VoteSummary query.
type OptionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	BallotCount   uint64                 `protobuf:"varint,3,opt,name=ballot_count,json=ballotCount,proto3" json:"ballot_count,omitempty"` // shares revealed for this (proposal, decision)
	TotalValue    uint64                 `protobuf:"varint,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`    // only populated when status = FINALIZED
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                     // Optional explanatory text shown under the option label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionSummary) Reset() {
	*x = OptionSummary{}
	mi := &file_svote_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionSummary) ProtoMessage() {}

func (x *OptionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionSummary.ProtoReflect.Descriptor instead.
func (*OptionSummary) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{20}
}

func (x *OptionSummary) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OptionSummary) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *OptionSummary) GetBallotCount() uint64 {
	if x != nil {
		return x.BallotCount
	}
	return 0
}

func (x *OptionSummary) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *OptionSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CeremonyState tracks the singleton EA key ceremony lifecycle.
type CeremonyState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             CeremonyStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=svote.v1.CeremonyStatus" json:"status,omitempty"`
	EaPk               []byte                 `protobuf:"bytes,2,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"`                                            // Set when DKG completes
	Validators         []*ValidatorPallasKey  `protobuf:"bytes,3,rep,name=validators,proto3" json:"validators,omitempty"`                                            // All registered pk_i
	Acks               []*AckEntry            `protobuf:"bytes,5,rep,name=acks,proto3" json:"acks,omitempty"`                                                        // Per-validator ack status
	PhaseStart         uint64                 `protobuf:"varint,7,opt,name=phase_start,json=phaseStart,proto3" json:"phase_start,omitempty"`                         // Unix seconds when current phase started
	PhaseTimeout       uint64                 `protobuf:"varint,8,opt,name=phase_timeout,json=phaseTimeout,proto3" json:"phase_timeout,omitempty"`                   // Timeout in seconds for current phase
	Threshold          uint32                 `protobuf:"varint,9,opt,name=threshold,proto3" json:"threshold,omitempty"`                                             // Minimum shares for reconstruction (always >= 1)
	FeldmanCommitments [][]byte               `protobuf:"bytes,10,rep,name=feldman_commitments,json=feldmanCommitments,proto3" json:"feldman_commitments,omitempty"` // C_j = a_j*G, t compressed Pallas points (32 bytes each)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CeremonyState) Reset() {
	*x = CeremonyState{}
	mi := &file_svote_v1_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CeremonyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeremonyState) ProtoMessage() {}

func (x *CeremonyState) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeremonyState.ProtoReflect.Descriptor instead.
func (*CeremonyState) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{21}
}

func (x *CeremonyState) GetStatus() CeremonyStatus {
	if x != nil {
		return x.Status
	}
	return CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED
}

func (x *CeremonyState) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *CeremonyState) GetValidators() []*ValidatorPallasKey {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *CeremonyState) GetAcks() []*AckEntry {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *CeremonyState) GetPhaseStart() uint64 {
	if x != nil {
		return x.PhaseStart
	}
	return 0
}

func (x *CeremonyState) GetPhaseTimeout() uint64 {
	if x != nil {
		return x.PhaseTimeout
	}
	return 0
}

func (x *CeremonyState) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CeremonyState) GetFeldmanCommitments() [][]byte {
	if x != nil {
		return x.FeldmanCommitments
	}
	return nil
}

// ValidatorPallasKey records a validator's registered Pallas public key.
type ValidatorPallasKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	PallasPk         []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"` // Compressed Pallas point (32 bytes)
	// shamir_index is the original 1-based Shamir evaluation point f(shamir_index)
	// assigned to this validator when the round ceremony was created. It is set
	// once at round creation and never changed, even when non-acking validators
	// are stripped from CeremonyValidators by StripNonAckersFromRound. Partial
	// decrypt injectors and the SubmitPartialDecryption handler must use this
	// field for Lagrange interpolation indices, not the post-stripping array position.
	ShamirIndex   uint32 `protobuf:"varint,3,opt,name=shamir_index,json=shamirIndex,proto3" json:"shamir_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorPallasKey) Reset() {
	*x = ValidatorPallasKey{}
	mi := &file_svote_v1_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorPallasKey) ProtoMessage() {}

func (x *ValidatorPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorPallasKey.ProtoReflect.Descriptor instead.
func (*ValidatorPallasKey) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{22}
}

func (x *ValidatorPallasKey) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *ValidatorPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

func (x *ValidatorPallasKey) GetShamirIndex() uint32 {
	if x != nil {
		return x.ShamirIndex
	}
	return 0
}

// DKGContribution holds one validator's contribution to the Joint-Feldman DKG.
// Each participant generates a random polynomial, publishes Feldman commitments,
// and ECIES-encrypts a share to every other participant.
type DKGContribution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress   string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	FeldmanCommitments [][]byte               `protobuf:"bytes,2,rep,name=feldman_commitments,json=feldmanCommitments,proto3" json:"feldman_commitments,omitempty"` // C_j = a_j*G for j=0..t-1
	Payloads           []*DealerPayload       `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`                                               // One ECIES envelope per ceremony validator
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DKGContribution) Reset() {
	*x = DKGContribution{}
	mi := &file_svote_v1_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGContribution) ProtoMessage() {}

func (x *DKGContribution) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGContribution.ProtoReflect.Descriptor instead.
func (*DKGContribution) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{23}
}

func (x *DKGContribution) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *DKGContribution) GetFeldmanCommitments() [][]byte {
	if x != nil {
		return x.FeldmanCommitments
	}
	return nil
}

func (x *DKGContribution) GetPayloads() []*DealerPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

// DealerPayload is an ECIES envelope from the dealer to a specific validator.
type DealerPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	EphemeralPk      []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pk,json=ephemeralPk,proto3" json:"ephemeral_pk,omitempty"` // E_i (32 bytes)
	Ciphertext       []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                      // ct_i: ChaCha20-Poly1305 (32 + 16 = 48 bytes)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DealerPayload) Reset() {
	*x = DealerPayload{}
	mi := &file_svote_v1_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealerPayload) ProtoMessage() {}

func (x *DealerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealerPayload.ProtoReflect.Descriptor instead.
func (*DealerPayload) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{24}
}

func (x *DealerPayload) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *DealerPayload) GetEphemeralPk() []byte {
	if x != nil {
		return x.EphemeralPk
	}
	return nil
}

func (x *DealerPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// AckEntry records a validator's acknowledgement of receiving their share.
type AckEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	AckSignature     []byte                 `protobuf:"bytes,2,opt,name=ack_signature,json=ackSignature,proto3" json:"ack_signature,omitempty"` // Commitment digest: SHA256("ack" || ea_pk || validator_address). Not a cryptographic signature; field name kept for wire compatibility.
	AckHeight        uint64                 `protobuf:"varint,3,opt,name=ack_height,json=ackHeight,proto3" json:"ack_height,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckEntry) Reset() {
	*x = AckEntry{}
	mi := &file_svote_v1_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEntry) ProtoMessage() {}

func (x *AckEntry) ProtoReflect() protoreflect.Message {
	mi := &file_svote_v1_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEntry.ProtoReflect.Descriptor instead.
func (*AckEntry) Descriptor() ([]byte, []int) {
	return file_svote_v1_types_proto_rawDescGZIP(), []int{25}
}

func (x *AckEntry) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *AckEntry) GetAckSignature() []byte {
	if x != nil {
		return x.AckSignature
	}
	return nil
}

func (x *AckEntry) GetAckHeight() uint64 {
	if x != nil {
		return x.AckHeight
	}
	return 0
}

var File_svote_v1_types_proto protoreflect.FileDescriptor

const file_svote_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14svote/v1/types.proto\x12\bsvote.v1\x1a\x19google/protobuf/any.proto\"Z\n" +
	"\n" +
	"VoteOption\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xbe\x01\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\aoptions\x18\x04 \x03(\v2\x14.svote.v1.VoteOptionR\aoptions\x12\x1d\n" +
	"\n" +
	"zip_number\x18\x05 \x01(\tR\tzipNumber\x12\x1b\n" +
	"\tforum_url\x18\x06 \x01(\tR\bforumUrl\"\xdb\t\n" +
	"\tVoteRound\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x18\n" +
	"\acreator\x18\b \x01(\tR\acreator\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.svote.v1.SessionStatusR\x06status\x12\x13\n" +
	"\x05ea_pk\x18\n" +
	" \x01(\fR\x04eaPk\x120\n" +
	"\tproposals\x18\v \x03(\v2\x12.svote.v1.ProposalR\tproposals\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12*\n" +
	"\x11created_at_height\x18\r \x01(\x04R\x0fcreatedAtHeight\x12\x14\n" +
	"\x05title\x18\x0e \x01(\tR\x05title\x12A\n" +
	"\x0fceremony_status\x18\x0f \x01(\x0e2\x18.svote.v1.CeremonyStatusR\x0eceremonyStatus\x12M\n" +
	"\x13ceremony_validators\x18\x10 \x03(\v2\x1c.svote.v1.ValidatorPallasKeyR\x12ceremonyValidators\x127\n" +
	"\rceremony_acks\x18\x12 \x03(\v2\x12.svote.v1.AckEntryR\fceremonyAcks\x120\n" +
	"\x14ceremony_phase_start\x18\x14 \x01(\x04R\x12ceremonyPhaseStart\x124\n" +
	"\x16ceremony_phase_timeout\x18\x15 \x01(\x04R\x14ceremonyPhaseTimeout\x12!\n" +
	"\fceremony_log\x18\x16 \x03(\tR\vceremonyLog\x12\x1c\n" +
	"\tthreshold\x18\x17 \x01(\rR\tthreshold\x12/\n" +
	"\x13feldman_commitments\x18\x18 \x03(\fR\x12feldmanCommitments\x12*\n" +
	"\x11tally_phase_start\x18\x19 \x01(\x04R\x0ftallyPhaseStart\x12.\n" +
	"\x13tally_phase_timeout\x18\x1a \x01(\x04R\x11tallyPhaseTimeout\x12&\n" +
	"\x0ftally_timed_out\x18\x1b \x01(\bR\rtallyTimedOut\x12F\n" +
	"\x11dkg_contributions\x18\x1c \x03(\v2\x19.svote.v1.DKGContributionR\x10dkgContributions\x12%\n" +
	"\x0ediscussion_url\x18\x1d \x01(\tR\rdiscussionUrl\x12&\n" +
	"\x0fcreated_at_time\x18\x1e \x01(\x04R\rcreatedAtTimeJ\x04\b\x11\x10\x12J\x04\b\x13\x10\x14\"L\n" +
	"\x0eVoteManagerSet\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\rR\tthreshold\"\xb4\x02\n" +
	"\x11CoordinatorAction\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12\x1a\n" +
	"\bproposer\x18\x03 \x01(\tR\bproposer\x12\x1c\n" +
	"\tapprovals\x18\x04 \x03(\tR\tapprovals\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.svote.v1.CoordinatorActionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x04R\texpiresAt\x12\x1f\n" +
	"\vexecuted_at\x18\b \x01(\x04R\n" +
	"executedAt\"\x8d\x01\n" +
	"\x13CommitmentTreeState\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x04R\tnextIndex\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12+\n" +
	"\x12next_index_at_root\x18\x04 \x01(\x04R\x0fnextIndexAtRoot\"\xe7\a\n" +
	"\fGenesisState\x12+\n" +
	"\x06rounds\x18\x01 \x03(\v2\x13.svote.v1.VoteRoundR\x06rounds\x128\n" +
	"\n" +
	"nullifiers\x18\x04 \x03(\v2\x18.svote.v1.NullifierEntryR\n" +
	"nullifiers\x124\n" +
	"\x16vote_manager_addresses\x18\x05 \x03(\tR\x14voteManagerAddresses\x12:\n" +
	"\rtally_results\x18\x06 \x03(\v2\x15.svote.v1.TallyResultR\ftallyResults\x12=\n" +
	"\vpallas_keys\x18\a \x03(\v2\x1c.svote.v1.ValidatorPallasKeyR\n" +
	"pallasKeys\x12P\n" +
	"\x12tally_accumulators\x18\b \x03(\v2!.svote.v1.GenesisTallyAccumulatorR\x11tallyAccumulators\x12>\n" +
	"\fshare_counts\x18\t \x03(\v2\x1b.svote.v1.GenesisShareCountR\vshareCounts\x126\n" +
	"\x17min_ceremony_validators\x18\v \x01(\rR\x15minCeremonyValidators\x12;\n" +
	"\vround_trees\x18\f \x03(\v2\x1a.svote.v1.GenesisRoundTreeR\n" +
	"roundTrees\x12S\n" +
	"\x13partial_decryptions\x18\r \x03(\v2\".svote.v1.GenesisPartialDecryptionR\x12partialDecryptions\x120\n" +
	"\tendorsers\x18\x0e \x03(\v2\x12.svote.v1.EndorserR\tendorsers\x12@\n" +
	"\x0fendorsed_rounds\x18\x0f \x03(\v2\x17.svote.v1.EndorsedRoundR\x0eendorsedRounds\x124\n" +
	"\x16vote_manager_threshold\x18\x10 \x01(\rR\x14voteManagerThreshold\x12L\n" +
	"\x13coordinator_actions\x18\x11 \x03(\v2\x1b.svote.v1.CoordinatorActionR\x12coordinatorActions\x12;\n" +
	"\x1anext_coordinator_action_id\x18\x12 \x01(\x04R\x17nextCoordinatorActionId\x12.\n" +
	"\x13used_delegation_rks\x18\x13 \x03(\fR\x11usedDelegationRks\"E\n" +
	"\bEndorser\x12\x1f\n" +
	"\vendorser_id\x18\x01 \x01(\tR\n" +
	"endorserId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"T\n" +
	"\rEndorsedRound\x12\x1f\n" +
	"\vendorser_id\x18\x01 \x01(\tR\n" +
	"endorserId\x12\"\n" +
	"\rvote_round_id\x18\x02 \x01(\fR\vvoteRoundId\"\xd6\x02\n" +
	"\x10GenesisRoundTree\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12<\n" +
	"\n" +
	"tree_state\x18\x02 \x01(\v2\x1d.svote.v1.CommitmentTreeStateR\ttreeState\x12E\n" +
	"\x11commitment_leaves\x18\x03 \x03(\v2\x18.svote.v1.CommitmentLeafR\x10commitmentLeaves\x12J\n" +
	"\x10commitment_roots\x18\x04 \x03(\v2\x1f.svote.v1.GenesisCommitmentRootR\x0fcommitmentRoots\x12M\n" +
	"\x12block_leaf_indices\x18\x05 \x03(\v2\x1f.svote.v1.GenesisBlockLeafIndexR\x10blockLeafIndices\"C\n" +
	"\x15GenesisCommitmentRoot\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\"\x9a\x01\n" +
	"\x17GenesisTallyAccumulator\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\fR\aroundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\"\x8a\x01\n" +
	"\x11GenesisShareCount\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\fR\aroundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"\xec\x01\n" +
	"\x18GenesisPartialDecryption\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\fR\aroundId\x12'\n" +
	"\x0fvalidator_index\x18\x02 \x01(\rR\x0evalidatorIndex\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x04 \x01(\rR\fvoteDecision\x12'\n" +
	"\x0fpartial_decrypt\x18\x05 \x01(\fR\x0epartialDecrypt\x12\x1d\n" +
	"\n" +
	"dleq_proof\x18\x06 \x01(\fR\tdleqProof\"f\n" +
	"\x15GenesisBlockLeafIndex\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vstart_index\x18\x02 \x01(\x04R\n" +
	"startIndex\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"<\n" +
	"\x0eCommitmentLeaf\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"p\n" +
	"\x0eNullifierEntry\x12\x1c\n" +
	"\tnullifier\x18\x01 \x01(\fR\tnullifier\x12%\n" +
	"\x0enullifier_type\x18\x02 \x01(\rR\rnullifierType\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\fR\aroundId\"\x98\x01\n" +
	"\vTallyResult\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x04R\n" +
	"totalValue\"w\n" +
	"\x10BlockCommitments\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vstart_index\x18\x02 \x01(\x04R\n" +
	"startIndex\x12\x16\n" +
	"\x06leaves\x18\x03 \x03(\fR\x06leaves\x12\x12\n" +
	"\x04root\x18\x04 \x01(\fR\x04root\"\x8c\x01\n" +
	"\x0fProposalSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\aoptions\x18\x04 \x03(\v2\x17.svote.v1.OptionSummaryR\aoptions\"\xa1\x01\n" +
	"\rOptionSummary\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\fballot_count\x18\x03 \x01(\x04R\vballotCount\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x04R\n" +
	"totalValue\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xdd\x02\n" +
	"\rCeremonyState\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.svote.v1.CeremonyStatusR\x06status\x12\x13\n" +
	"\x05ea_pk\x18\x02 \x01(\fR\x04eaPk\x12<\n" +
	"\n" +
	"validators\x18\x03 \x03(\v2\x1c.svote.v1.ValidatorPallasKeyR\n" +
	"validators\x12&\n" +
	"\x04acks\x18\x05 \x03(\v2\x12.svote.v1.AckEntryR\x04acks\x12\x1f\n" +
	"\vphase_start\x18\a \x01(\x04R\n" +
	"phaseStart\x12#\n" +
	"\rphase_timeout\x18\b \x01(\x04R\fphaseTimeout\x12\x1c\n" +
	"\tthreshold\x18\t \x01(\rR\tthreshold\x12/\n" +
	"\x13feldman_commitments\x18\n" +
	" \x03(\fR\x12feldmanCommitmentsJ\x04\b\x04\x10\x05J\x04\b\x06\x10\a\"\x81\x01\n" +
	"\x12ValidatorPallasKey\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\x12!\n" +
	"\fshamir_index\x18\x03 \x01(\rR\vshamirIndex\"\xa4\x01\n" +
	"\x0fDKGContribution\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12/\n" +
	"\x13feldman_commitments\x18\x02 \x03(\fR\x12feldmanCommitments\x123\n" +
	"\bpayloads\x18\x03 \x03(\v2\x17.svote.v1.DealerPayloadR\bpayloads\"\x7f\n" +
	"\rDealerPayload\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12!\n" +
	"\fephemeral_pk\x18\x02 \x01(\fR\vephemeralPk\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\"{\n" +
	"\bAckEntry\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12#\n" +
	"\rack_signature\x18\x02 \x01(\fR\fackSignature\x12\x1d\n" +
	"\n" +
	"ack_height\x18\x03 \x01(\x04R\tackHeight*\xc5\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SESSION_STATUS_TALLYING\x10\x02\x12\x1c\n" +
	"\x18SESSION_STATUS_FINALIZED\x10\x03\x12\x1a\n" +
	"\x16SESSION_STATUS_PENDING\x10\x04\x12\"\n" +
	"\x1eSESSION_STATUS_CEREMONY_FAILED\x10\x05*\xba\x01\n" +
	"\x17CoordinatorActionStatus\x12)\n" +
	"%COORDINATOR_ACTION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!COORDINATOR_ACTION_STATUS_PENDING\x10\x01\x12&\n" +
	"\"COORDINATOR_ACTION_STATUS_EXECUTED\x10\x02\x12%\n" +
	"!COORDINATOR_ACTION_STATUS_EXPIRED\x10\x03*\x8c\x01\n" +
	"\x0eCeremonyStatus\x12\x1f\n" +
	"\x1bCEREMONY_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCEREMONY_STATUS_REGISTERING\x10\x01\x12\x19\n" +
	"\x15CEREMONY_STATUS_DEALT\x10\x02\x12\x1d\n" +
	"\x19CEREMONY_STATUS_CONFIRMED\x10\x03B-Z+github.com/valargroup/vote-sdk/x/vote/typesb\x06proto3"

var (
	file_svote_v1_types_proto_rawDescOnce sync.Once
	file_svote_v1_types_proto_rawDescData []byte
)

func file_svote_v1_types_proto_rawDescGZIP() []byte {
	file_svote_v1_types_proto_rawDescOnce.Do(func() {
		file_svote_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svote_v1_types_proto_rawDesc), len(file_svote_v1_types_proto_rawDesc)))
	})
	return file_svote_v1_types_proto_rawDescData
}

var file_svote_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_svote_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_svote_v1_types_proto_goTypes = []any{
	(SessionStatus)(0),               // 0: svote.v1.SessionStatus
	(CoordinatorActionStatus)(0),     // 1: svote.v1.CoordinatorActionStatus
	(CeremonyStatus)(0),              // 2: svote.v1.CeremonyStatus
	(*VoteOption)(nil),               // 3: svote.v1.VoteOption
	(*Proposal)(nil),                 // 4: svote.v1.Proposal
	(*VoteRound)(nil),                // 5: svote.v1.VoteRound
	(*VoteManagerSet)(nil),           // 6: svote.v1.VoteManagerSet
	(*CoordinatorAction)(nil),        // 7: svote.v1.CoordinatorAction
	(*CommitmentTreeState)(nil),      // 8: svote.v1.CommitmentTreeState
	(*GenesisState)(nil),             // 9: svote.v1.GenesisState
	(*Endorser)(nil),                 // 10: svote.v1.Endorser
	(*EndorsedRound)(nil),            // 11: svote.v1.EndorsedRound
	(*GenesisRoundTree)(nil),         // 12: svote.v1.GenesisRoundTree
	(*GenesisCommitmentRoot)(nil),    // 13: svote.v1.GenesisCommitmentRoot
	(*GenesisTallyAccumulator)(nil),  // 14: svote.v1.GenesisTallyAccumulator
	(*GenesisShareCount)(nil),        // 15: svote.v1.GenesisShareCount
	(*GenesisPartialDecryption)(nil), // 16: svote.v1.GenesisPartialDecryption
	(*GenesisBlockLeafIndex)(nil),    // 17: svote.v1.GenesisBlockLeafIndex
	(*CommitmentLeaf)(nil),           // 18: svote.v1.CommitmentLeaf
	(*NullifierEntry)(nil),           // 19: svote.v1.NullifierEntry
	(*TallyResult)(nil),              // 20: svote.v1.TallyResult
	(*BlockCommitments)(nil),         // 21: svote.v1.BlockCommitments
	(*ProposalSummary)(nil),          // 22: svote.v1.ProposalSummary
	(*OptionSummary)(nil),            // 23: svote.v1.OptionSummary
	(*CeremonyState)(nil),            // 24: svote.v1.CeremonyState
	(*ValidatorPallasKey)(nil),       // 25: svote.v1.ValidatorPallasKey
	(*DKGContribution)(nil),          // 26: svote.v1.DKGContribution
	(*DealerPayload)(nil),            // 27: svote.v1.DealerPayload
	(*AckEntry)(nil),                 // 28: svote.v1.AckEntry
	(*anypb.Any)(nil),                // 29: google.protobuf.Any
}
var file_svote_v1_types_proto_depIdxs = []int32{
	3,  // 0: svote.v1.Proposal.options:type_name -> svote.v1.VoteOption
	0,  // 1: svote.v1.VoteRound.status:type_name -> svote.v1.SessionStatus
	4,  // 2: svote.v1.VoteRound.proposals:type_name -> svote.v1.Proposal
	2,  // 3: svote.v1.VoteRound.ceremony_status:type_name -> svote.v1.CeremonyStatus
	25, // 4: svote.v1.VoteRound.ceremony_validators:type_name -> svote.v1.ValidatorPallasKey
	28, // 5: svote.v1.VoteRound.ceremony_acks:type_name -> svote.v1.AckEntry
	26, // 6: svote.v1.VoteRound.dkg_contributions:type_name -> svote.v1.DKGContribution
	29, // 7: svote.v1.CoordinatorAction.payload:type_name -> google.protobuf.Any
	1,  // 8: svote.v1.CoordinatorAction.status:type_name -> svote.v1.CoordinatorActionStatus
	5,  // 9: svote.v1.GenesisState.rounds:type_name -> svote.v1.VoteRound
	19, // 10: svote.v1.GenesisState.nullifiers:type_name -> svote.v1.NullifierEntry
	20, // 11: svote.v1.GenesisState.tally_results:type_name -> svote.v1.TallyResult
	25, // 12: svote.v1.GenesisState.pallas_keys:type_name -> svote.v1.ValidatorPallasKey
	14, // 13: svote.v1.GenesisState.tally_accumulators:type_name -> svote.v1.GenesisTallyAccumulator
	15, // 14: svote.v1.GenesisState.share_counts:type_name -> svote.v1.GenesisShareCount
	12, // 15: svote.v1.GenesisState.round_trees:type_name -> svote.v1.GenesisRoundTree
	16, // 16: svote.v1.GenesisState.partial_decryptions:type_name -> svote.v1.GenesisPartialDecryption
	10, // 17: svote.v1.GenesisState.endorsers:type_name -> svote.v1.Endorser
	11, // 18: svote.v1.GenesisState.endorsed_rounds:type_name -> svote.v1.EndorsedRound
	7,  // 19: svote.v1.GenesisState.coordinator_actions:type_name -> svote.v1.CoordinatorAction
	8,  // 20: svote.v1.GenesisRoundTree.tree_state:type_name -> svote.v1.CommitmentTreeState
	18, // 21: svote.v1.GenesisRoundTree.commitment_leaves:type_name -> svote.v1.CommitmentLeaf
	13, // 22: svote.v1.GenesisRoundTree.commitment_roots:type_name -> svote.v1.GenesisCommitmentRoot
	17, // 23: svote.v1.GenesisRoundTree.block_leaf_indices:type_name -> svote.v1.GenesisBlockLeafIndex
	23, // 24: svote.v1.ProposalSummary.options:type_name -> svote.v1.OptionSummary
	2,  // 25: svote.v1.CeremonyState.status:type_name -> svote.v1.CeremonyStatus
	25, // 26: svote.v1.CeremonyState.validators:type_name -> svote.v1.ValidatorPallasKey
	28, // 27: svote.v1.CeremonyState.acks:type_name -> svote.v1.AckEntry
	27, // 28: svote.v1.DKGContribution.payloads:type_name -> svote.v1.DealerPayload
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_svote_v1_types_proto_init() }
func file_svote_v1_types_proto_init() {
	if File_svote_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svote_v1_types_proto_rawDesc), len(file_svote_v1_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svote_v1_types_proto_goTypes,
		DependencyIndexes: file_svote_v1_types_proto_depIdxs,
		EnumInfos:         file_svote_v1_types_proto_enumTypes,
		MessageInfos:      file_svote_v1_types_proto_msgTypes,
	}.Build()
	File_svote_v1_types_proto = out.File
	file_svote_v1_types_proto_goTypes = nil
	file_svote_v1_types_proto_depIdxs = nil
}
